//! CMake generation for the C++ backend.
//!
//! Emits a single normative top-level `CMakeLists.txt` configured for an
//! MSVC-ABI static library — no compiler/toolchain coupling. Builders pick
//! their toolchain (vanilla MSVC on Windows, `clang-cl` + xwin on Linux,
//! etc.) via `-DCMAKE_TOOLCHAIN_FILE=...`. The pyxis repo ships a sample
//! xwin/clang-cl toolchain at `tools/cmake-toolchains/xwin-x86.cmake` for
//! Linux dev-loop iteration; that file is not part of the per-project
//! codegen output.

use std::path::Path;

use crate::{
    backends::{BackendError, Result},
    config::Project,
};

/// Emit `<out_dir>/CMakeLists.txt`. The output is normative MSVC-ABI: no
/// compiler/toolchain coupling, no Linux-specific concerns. Builders supply
/// their own toolchain file.
pub fn write_cmake(out_dir: &Path, project: &Project) -> Result<()> {
    let project_name = sanitize_target_name(&project.name);
    let pointer_size = project.pointer_size;
    let bits = pointer_size * 8;
    let raw_name = &project.name;

    let cmake = format!(
        r#"# @generated by pyxis — do not edit
cmake_minimum_required(VERSION 3.20)
project({project_name} CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Sanity check: pyxis.toml's pointer_size ({pointer_size}) must match the toolchain's pointer size.
if(NOT CMAKE_SIZEOF_VOID_P EQUAL {pointer_size})
    message(FATAL_ERROR "pyxis project '{raw_name}' expects pointer size {pointer_size} but toolchain has ${{CMAKE_SIZEOF_VOID_P}}. Use a {bits}-bit MSVC env.")
endif()

file(GLOB_RECURSE PYXIS_SRC CONFIGURE_DEPENDS "src/*.cpp")
file(GLOB_RECURSE PYXIS_HDR CONFIGURE_DEPENDS "include/*.hpp")

if(PYXIS_SRC)
    add_library({project_name} STATIC ${{PYXIS_SRC}} ${{PYXIS_HDR}})
else()
    add_library({project_name} INTERFACE)
endif()

if(TARGET {project_name})
    get_target_property(_pyxis_type {project_name} TYPE)
    if(_pyxis_type STREQUAL "INTERFACE_LIBRARY")
        target_include_directories({project_name} INTERFACE include)
    else()
        target_include_directories({project_name} PUBLIC include)
        target_compile_features({project_name} PUBLIC cxx_std_17)
    endif()
endif()
"#
    );

    let cmake_path = out_dir.join("CMakeLists.txt");
    std::fs::write(&cmake_path, cmake).map_err(|e| BackendError::Io {
        error: e,
        context: format!("Failed to write {}", cmake_path.display()),
    })?;
    Ok(())
}

fn sanitize_target_name(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}
