//! CMake / runtime-header generation for the C++ backend.
//!
//! Produces a top-level `CMakeLists.txt` configured for an MSVC-ABI static
//! library, a `cmake-toolchains/xwin-x86.cmake` toolchain file that drives
//! `clang-cl` against an xwin-provisioned MSVC SDK on Linux dev hosts, and
//! `include/pyxis_runtime.hpp` (calling-convention macro shim + opaque
//! atomic placeholders).
//!
//! All output is plain text built up via `format!`; no templating engine.

use std::fmt::Write as _;
use std::path::Path;

use crate::{
    backends::{BackendError, Result},
    config::Project,
};

/// Emit `<out_dir>/CMakeLists.txt` and `<out_dir>/cmake-toolchains/xwin-x86.cmake`.
pub fn write_cmake(out_dir: &Path, project: &Project) -> Result<()> {
    let project_name = sanitize_target_name(&project.name);

    // Top-level CMakeLists.
    let mut cmake = String::new();
    writeln!(cmake, "# @generated by pyxis — do not edit").unwrap();
    writeln!(cmake, "cmake_minimum_required(VERSION 3.20)").unwrap();
    writeln!(cmake, "project({project_name} CXX)").unwrap();
    writeln!(cmake).unwrap();
    writeln!(cmake, "set(CMAKE_CXX_STANDARD 17)").unwrap();
    writeln!(cmake, "set(CMAKE_CXX_STANDARD_REQUIRED ON)").unwrap();
    writeln!(cmake).unwrap();
    writeln!(
        cmake,
        "# Sanity check: pointer_size from pyxis.toml ({}) must match the toolchain's pointer size.",
        project.pointer_size
    )
    .unwrap();
    writeln!(
        cmake,
        "if(NOT CMAKE_SIZEOF_VOID_P EQUAL {})",
        project.pointer_size
    )
    .unwrap();
    writeln!(
        cmake,
        "    message(FATAL_ERROR \"pyxis project '{}' expects pointer size {} but toolchain has \\${{CMAKE_SIZEOF_VOID_P}}. Use cmake-toolchains/xwin-x86.cmake or an x86 MSVC env.\")",
        project.name, project.pointer_size
    )
    .unwrap();
    writeln!(cmake, "endif()").unwrap();
    writeln!(cmake).unwrap();
    writeln!(
        cmake,
        "file(GLOB_RECURSE PYXIS_SRC CONFIGURE_DEPENDS \"src/**/*.cpp\")"
    )
    .unwrap();
    writeln!(cmake, "file(GLOB_RECURSE PYXIS_HDR CONFIGURE_DEPENDS \"include/**/*.hpp\")").unwrap();
    writeln!(cmake).unwrap();
    writeln!(cmake, "if(PYXIS_SRC)").unwrap();
    writeln!(
        cmake,
        "    add_library({project_name} STATIC ${{PYXIS_SRC}} ${{PYXIS_HDR}})"
    )
    .unwrap();
    writeln!(cmake, "else()").unwrap();
    // Header-only modules: emit an INTERFACE library so consumers can still
    // depend on the include tree.
    writeln!(cmake, "    add_library({project_name} INTERFACE)").unwrap();
    writeln!(cmake, "endif()").unwrap();
    writeln!(cmake).unwrap();
    writeln!(cmake, "if(TARGET {project_name})").unwrap();
    writeln!(cmake, "    get_target_property(_pyxis_type {project_name} TYPE)").unwrap();
    writeln!(cmake, "    if(_pyxis_type STREQUAL \"INTERFACE_LIBRARY\")").unwrap();
    writeln!(
        cmake,
        "        target_include_directories({project_name} INTERFACE include)"
    )
    .unwrap();
    writeln!(cmake, "    else()").unwrap();
    writeln!(
        cmake,
        "        target_include_directories({project_name} PUBLIC include)"
    )
    .unwrap();
    writeln!(
        cmake,
        "        target_compile_features({project_name} PUBLIC cxx_std_17)"
    )
    .unwrap();
    writeln!(cmake, "    endif()").unwrap();
    writeln!(cmake, "endif()").unwrap();

    let cmake_path = out_dir.join("CMakeLists.txt");
    std::fs::write(&cmake_path, &cmake).map_err(|e| BackendError::Io {
        error: e,
        context: format!("Failed to write {}", cmake_path.display()),
    })?;

    // xwin-x86 toolchain file (used on Linux dev hosts; on real Windows MSVC,
    // the user just runs cmake directly without this file).
    let mut toolchain = String::new();
    writeln!(toolchain, "# @generated by pyxis — do not edit").unwrap();
    writeln!(
        toolchain,
        "# Toolchain for building pyxis-emitted MSVC-ABI code on Linux dev hosts"
    )
    .unwrap();
    writeln!(
        toolchain,
        "# via clang-cl + xwin-provisioned MSVC headers/libs."
    )
    .unwrap();
    writeln!(toolchain, "#").unwrap();
    writeln!(
        toolchain,
        "# Prerequisites:"
    )
    .unwrap();
    writeln!(toolchain, "#   1. xwin (https://github.com/Jake-Shadle/xwin):").unwrap();
    writeln!(
        toolchain,
        "#        xwin --accept-license splat --output ~/.xwin"
    )
    .unwrap();
    writeln!(toolchain, "#   2. clang-cl/lld-link from a recent LLVM (>= 16).").unwrap();
    writeln!(toolchain, "#").unwrap();
    writeln!(
        toolchain,
        "# Usage:"
    )
    .unwrap();
    writeln!(
        toolchain,
        "#   cmake -S . -B build \\"
    )
    .unwrap();
    writeln!(
        toolchain,
        "#     -DCMAKE_TOOLCHAIN_FILE=cmake-toolchains/xwin-x86.cmake \\"
    )
    .unwrap();
    writeln!(toolchain, "#     -DXWIN_ROOT=$HOME/.xwin/splat").unwrap();
    writeln!(toolchain, "#   cmake --build build -j").unwrap();
    writeln!(toolchain).unwrap();
    writeln!(toolchain, "set(CMAKE_SYSTEM_NAME Windows)").unwrap();
    writeln!(toolchain, "set(CMAKE_SYSTEM_PROCESSOR x86)").unwrap();
    writeln!(toolchain).unwrap();
    writeln!(
        toolchain,
        "if(NOT DEFINED XWIN_ROOT)"
    )
    .unwrap();
    writeln!(
        toolchain,
        "    if(DEFINED ENV{{XWIN_ROOT}})"
    )
    .unwrap();
    writeln!(toolchain, "        set(XWIN_ROOT $ENV{{XWIN_ROOT}})").unwrap();
    writeln!(toolchain, "    else()").unwrap();
    writeln!(
        toolchain,
        "        message(FATAL_ERROR \"XWIN_ROOT not set. Pass -DXWIN_ROOT=<path> or export XWIN_ROOT=<path>; see cmake-toolchains/xwin-x86.cmake header for setup.\")"
    )
    .unwrap();
    writeln!(toolchain, "    endif()").unwrap();
    writeln!(toolchain, "endif()").unwrap();
    writeln!(toolchain).unwrap();
    writeln!(toolchain, "set(CMAKE_C_COMPILER clang-cl)").unwrap();
    writeln!(toolchain, "set(CMAKE_CXX_COMPILER clang-cl)").unwrap();
    writeln!(toolchain, "set(CMAKE_LINKER lld-link)").unwrap();
    writeln!(toolchain, "set(CMAKE_AR llvm-lib)").unwrap();
    writeln!(toolchain, "set(CMAKE_RC_COMPILER llvm-rc)").unwrap();
    writeln!(toolchain).unwrap();
    writeln!(toolchain, "set(CLANG_TARGET \"--target=i686-pc-windows-msvc\")").unwrap();
    writeln!(
        toolchain,
        "set(XWIN_FLAGS \"-vctoolsdir ${{XWIN_ROOT}}/crt -winsdkdir ${{XWIN_ROOT}}/sdk\")"
    )
    .unwrap();
    writeln!(toolchain).unwrap();
    writeln!(
        toolchain,
        "set(CMAKE_C_FLAGS_INIT \"${{CLANG_TARGET}} ${{XWIN_FLAGS}} /imsvc ${{XWIN_ROOT}}/crt/include /imsvc ${{XWIN_ROOT}}/sdk/include/ucrt /imsvc ${{XWIN_ROOT}}/sdk/include/um /imsvc ${{XWIN_ROOT}}/sdk/include/shared\")"
    )
    .unwrap();
    writeln!(
        toolchain,
        "set(CMAKE_CXX_FLAGS_INIT \"${{CLANG_TARGET}} ${{XWIN_FLAGS}} /imsvc ${{XWIN_ROOT}}/crt/include /imsvc ${{XWIN_ROOT}}/sdk/include/ucrt /imsvc ${{XWIN_ROOT}}/sdk/include/um /imsvc ${{XWIN_ROOT}}/sdk/include/shared\")"
    )
    .unwrap();
    writeln!(toolchain).unwrap();
    writeln!(
        toolchain,
        "set(CMAKE_EXE_LINKER_FLAGS_INIT \"/libpath:${{XWIN_ROOT}}/crt/lib/x86 /libpath:${{XWIN_ROOT}}/sdk/lib/ucrt/x86 /libpath:${{XWIN_ROOT}}/sdk/lib/um/x86\")"
    )
    .unwrap();
    writeln!(
        toolchain,
        "set(CMAKE_STATIC_LINKER_FLAGS_INIT \"/libpath:${{XWIN_ROOT}}/crt/lib/x86 /libpath:${{XWIN_ROOT}}/sdk/lib/ucrt/x86 /libpath:${{XWIN_ROOT}}/sdk/lib/um/x86\")"
    )
    .unwrap();
    writeln!(
        toolchain,
        "set(CMAKE_MODULE_LINKER_FLAGS_INIT \"${{CMAKE_EXE_LINKER_FLAGS_INIT}}\")"
    )
    .unwrap();
    writeln!(
        toolchain,
        "set(CMAKE_SHARED_LINKER_FLAGS_INIT \"${{CMAKE_EXE_LINKER_FLAGS_INIT}}\")"
    )
    .unwrap();
    writeln!(toolchain).unwrap();
    writeln!(toolchain, "set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)").unwrap();
    writeln!(toolchain, "set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)").unwrap();
    writeln!(toolchain, "set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)").unwrap();
    writeln!(toolchain, "set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)").unwrap();

    let toolchain_dir = out_dir.join("cmake-toolchains");
    std::fs::create_dir_all(&toolchain_dir).map_err(|e| BackendError::Io {
        error: e,
        context: format!("Failed to create {}", toolchain_dir.display()),
    })?;
    let toolchain_path = toolchain_dir.join("xwin-x86.cmake");
    std::fs::write(&toolchain_path, &toolchain).map_err(|e| BackendError::Io {
        error: e,
        context: format!("Failed to write {}", toolchain_path.display()),
    })?;

    Ok(())
}

fn sanitize_target_name(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}
