//! C++ backend.
//!
//! Emits one `.hpp` per pyxis module (with forward-decls + includes + full
//! definitions in a single header), plus a top-level `CMakeLists.txt`,
//! `pyxis_runtime.hpp`, and `cmake-toolchains/xwin-x86.cmake` so the project
//! compiles into a static library targeting MSVC ABI.
//!
//! Phase 1 status: structs / enums / bitflags / type aliases. Vftables,
//! functions, generics, externs, per-module prologue/epilogue, and CMake
//! generation are filled in by later phases.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::{
    backends::{BackendError, Result},
    config::Project,
    grammar::ItemPath,
    semantic::{Module, ResolvedSemanticState, types::ItemDefinitionInner},
};

mod cmake;
mod deps;
mod render;

/// Emit `<out_dir>/include/<module>/...hpp` for a single module.
pub fn write_module(
    out_dir: &Path,
    key: &ItemPath,
    semantic_state: &ResolvedSemanticState,
    module: &Module,
) -> Result<()> {
    if key.is_empty() {
        return Ok(());
    }

    let registry = semantic_state.type_registry();
    let module_deps = deps::collect_module_deps(key, module, registry);

    let mut body = String::new();
    let mut wrote_anything = false;
    let mut sorted_items: Vec<_> = module.definitions(registry).collect();
    sorted_items.sort_by_key(|d| d.path.clone());
    for item in sorted_items {
        let Some(text) = render::render_item(item, key, registry)? else {
            continue;
        };
        if wrote_anything {
            writeln!(body)?;
        }
        body.push_str(&text);
        wrote_anything = true;
    }

    if !wrote_anything && module_deps.include_modules.is_empty() {
        return Ok(());
    }

    let header_path = module_to_header_path(out_dir, key);
    if let Some(parent) = header_path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| BackendError::Io {
            error: e,
            context: format!("Failed to create directory {}", parent.display()),
        })?;
    }

    let mut out = String::new();
    writeln!(out, "// @generated by pyxis — do not edit")?;
    writeln!(out, "#pragma once")?;
    writeln!(out)?;
    writeln!(out, "#include <cstdint>")?;
    writeln!(out, "#include <cstddef>")?;
    writeln!(out, "#include \"pyxis_runtime.hpp\"")?;

    // Includes for FullDef cross-module deps.
    if !module_deps.include_modules.is_empty() {
        writeln!(out)?;
        for dep_module in &module_deps.include_modules {
            let path = module_to_relative_include(dep_module);
            writeln!(out, "#include \"{path}\"")?;
        }
    }

    // Forward declarations for FwdOnly cross-module deps.
    if !module_deps.forward_decls.is_empty() {
        writeln!(out)?;
        for (dep_module, items) in &module_deps.forward_decls {
            open_namespace(&mut out, dep_module)?;
            for item_path in items {
                let leaf = item_path.last().map(|s| s.as_str()).unwrap_or("");
                let kind = forward_decl_kind(item_path, semantic_state);
                writeln!(out, "    {kind} {leaf};")?;
            }
            close_namespace(&mut out, dep_module)?;
        }
    }

    if wrote_anything {
        writeln!(out)?;
        open_namespace(&mut out, key)?;
        // Intra-module forward declarations: every non-alias, non-generic
        // resolved item gets a forward decl up top so pointer-typed fields
        // can reference peers defined later in the file.
        let mut intra_fwd: Vec<(&str, &'static str)> = Vec::new();
        for item in module.definitions(registry) {
            if item.is_predefined()
                || matches!(item.category, crate::semantic::types::ItemCategory::Extern)
                || item.is_generic()
            {
                continue;
            }
            let Some(resolved) = item.resolved() else {
                continue;
            };
            let kind = match &resolved.inner {
                ItemDefinitionInner::Type(_) => "struct",
                ItemDefinitionInner::Enum(_) | ItemDefinitionInner::Bitflags(_) => continue,
                ItemDefinitionInner::TypeAlias(_) => continue,
            };
            if let Some(leaf) = item.path.last() {
                intra_fwd.push((leaf.as_str(), kind));
            }
        }
        intra_fwd.sort();
        intra_fwd.dedup();
        if !intra_fwd.is_empty() {
            for (leaf, kind) in &intra_fwd {
                writeln!(out, "    {kind} {leaf};")?;
            }
            writeln!(out)?;
        }
        for line in body.lines() {
            if line.is_empty() {
                writeln!(out)?;
            } else {
                writeln!(out, "    {line}")?;
            }
        }
        close_namespace(&mut out, key)?;
    }

    std::fs::write(&header_path, &out).map_err(|e| BackendError::Io {
        error: e,
        context: format!("Failed to write header to {}", header_path.display()),
    })?;
    Ok(())
}

/// Emit `<out_dir>/include/pyxis_runtime.hpp` — shared typedefs / utility
/// templates used by every generated module.
pub fn write_runtime_header(out_dir: &Path) -> Result<()> {
    let path = out_dir.join("include").join("pyxis_runtime.hpp");
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| BackendError::Io {
            error: e,
            context: format!("Failed to create directory {}", parent.display()),
        })?;
    }

    // Phase 1 placeholder — atomic types map to size-correct opaque structs
    // until Phase 3 lets us pull in `<atomic>` via cpp_header on extern types.
    let mut out = String::new();
    writeln!(&mut out, "// @generated by pyxis — do not edit")?;
    writeln!(&mut out, "#pragma once")?;
    writeln!(&mut out)?;
    writeln!(&mut out, "#include <cstdint>")?;
    writeln!(&mut out)?;
    writeln!(&mut out, "namespace pyxis {{")?;
    for (name, size) in [
        ("AtomicBool", 1usize),
        ("AtomicU8", 1),
        ("AtomicU16", 2),
        ("AtomicU32", 4),
        ("AtomicU64", 8),
        ("AtomicI8", 1),
        ("AtomicI16", 2),
        ("AtomicI32", 4),
        ("AtomicI64", 8),
    ] {
        writeln!(
            &mut out,
            "struct alignas({size}) {name} {{ ::std::uint8_t _bytes[{size}]; }};"
        )?;
    }
    writeln!(&mut out, "}} // namespace pyxis")?;

    std::fs::write(&path, &out).map_err(|e| BackendError::Io {
        error: e,
        context: format!("Failed to write {}", path.display()),
    })?;
    Ok(())
}

/// Emit `<out_dir>/CMakeLists.txt` and `<out_dir>/cmake-toolchains/xwin-x86.cmake`.
pub fn write_cmake(_out_dir: &Path, _project: &Project) -> Result<()> {
    // Phase 4 fills this in.
    Ok(())
}

fn module_to_header_path(out_dir: &Path, module_path: &ItemPath) -> PathBuf {
    let mut p = out_dir.join("include");
    let segs: Vec<_> = module_path.iter().collect();
    for (i, seg) in segs.iter().enumerate() {
        if i + 1 == segs.len() {
            p.push(format!("{}.hpp", seg.as_str()));
        } else {
            p.push(seg.as_str());
        }
    }
    p
}

fn module_to_relative_include(module_path: &ItemPath) -> String {
    let mut s = String::new();
    let segs: Vec<_> = module_path.iter().collect();
    for (i, seg) in segs.iter().enumerate() {
        if i > 0 {
            s.push('/');
        }
        s.push_str(seg.as_str());
    }
    s.push_str(".hpp");
    s
}

fn open_namespace(out: &mut String, module_path: &ItemPath) -> Result<()> {
    write!(out, "namespace ")?;
    for (i, seg) in module_path.iter().enumerate() {
        if i > 0 {
            write!(out, "::")?;
        }
        write!(out, "{}", seg.as_str())?;
    }
    writeln!(out, " {{")?;
    Ok(())
}

fn close_namespace(out: &mut String, module_path: &ItemPath) -> Result<()> {
    write!(out, "}} // namespace ")?;
    for (i, seg) in module_path.iter().enumerate() {
        if i > 0 {
            write!(out, "::")?;
        }
        write!(out, "{}", seg.as_str())?;
    }
    writeln!(out)?;
    Ok(())
}

fn forward_decl_kind(item_path: &ItemPath, semantic_state: &ResolvedSemanticState) -> &'static str {
    let registry = semantic_state.type_registry();
    if let Ok(item) = registry.get(item_path, &crate::span::ItemLocation::internal())
        && let Some(resolved) = item.resolved()
    {
        return match &resolved.inner {
            ItemDefinitionInner::Type(_) => "struct",
            ItemDefinitionInner::Enum(_) | ItemDefinitionInner::Bitflags(_) => {
                // Forward-declaring an enum requires its underlying type;
                // skip the safer-but-broken option and fall back to `struct`
                // — Phase 3 will refine this once we emit the underlying
                // type alongside.
                "enum class"
            }
            ItemDefinitionInner::TypeAlias(_) => "struct",
        };
    }
    "struct"
}
