// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace atomics {
    struct AtomicCounters;

    /// Test type using atomic primitives
    struct alignas(8) AtomicCounters {
        ::pyxis::AtomicBool bool_flag;
        ::pyxis::AtomicU8 counter_u8;
        ::pyxis::AtomicU16 counter_u16;
        ::pyxis::AtomicU32 counter_u32;
        ::pyxis::AtomicU64 counter_u64;
        ::pyxis::AtomicI8 counter_i8;
        ::std::uint8_t _field_11[1];
        ::pyxis::AtomicI16 counter_i16;
        ::pyxis::AtomicI32 counter_i32;
        ::pyxis::AtomicI64 counter_i64;
    };
    static_assert(sizeof(AtomicCounters) == 0x20);
    static_assert(alignof(AtomicCounters) == 8);
} // namespace atomics
