// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

using HandleRaw = ::std::uint8_t*;

namespace backend_for {
    struct Handle;
    struct Widget;

    struct alignas(8) Handle {
        ::std::uint8_t* raw;
        static Handle null();
    };
    static_assert(sizeof(Handle) == 0x8);
    static_assert(alignof(Handle) == 8);

    struct alignas(4) Widget {
        ::std::uint32_t id;
        static Widget make();
        ::std::uint32_t get_id() const;
    };
    static_assert(sizeof(Widget) == 0x4);
    static_assert(alignof(Widget) == 4);

    ::std::uint32_t module_init();

    inline Widget Widget::make() { return Widget{0}; }
    inline ::std::uint32_t Widget::get_id() const { return id; }

    inline ::std::uint32_t module_init() { return 1; }

    inline Handle Handle::null() { return Handle{nullptr}; }
} // namespace backend_for
