// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace bitflags {
    enum class TestBitflags : ::std::uint32_t;
    enum class TestBitflags2 : ::std::uint32_t;

    enum class TestBitflags : ::std::uint32_t {
        NONE = 0x0,
        FLAG_1 = 0x1,
        FLAG_2 = 0x2,
        FLAG_3 = 0x4,
    };
    constexpr TestBitflags operator|(TestBitflags a, TestBitflags b) noexcept {
        return static_cast<TestBitflags>(static_cast<::std::uint32_t>(a) | static_cast<::std::uint32_t>(b));
    }
    constexpr TestBitflags operator&(TestBitflags a, TestBitflags b) noexcept {
        return static_cast<TestBitflags>(static_cast<::std::uint32_t>(a) & static_cast<::std::uint32_t>(b));
    }
    constexpr TestBitflags operator^(TestBitflags a, TestBitflags b) noexcept {
        return static_cast<TestBitflags>(static_cast<::std::uint32_t>(a) ^ static_cast<::std::uint32_t>(b));
    }
    constexpr TestBitflags operator~(TestBitflags a) noexcept {
        return static_cast<TestBitflags>(~static_cast<::std::uint32_t>(a));
    }
    static_assert(sizeof(TestBitflags) == 0x4);

    enum class TestBitflags2 : ::std::uint32_t {
        NONE = 0x0,
        FLAG_1 = 0x1,
        FLAG_2 = 0x2,
        FLAG_3 = 0x4,
    };
    constexpr TestBitflags2 operator|(TestBitflags2 a, TestBitflags2 b) noexcept {
        return static_cast<TestBitflags2>(static_cast<::std::uint32_t>(a) | static_cast<::std::uint32_t>(b));
    }
    constexpr TestBitflags2 operator&(TestBitflags2 a, TestBitflags2 b) noexcept {
        return static_cast<TestBitflags2>(static_cast<::std::uint32_t>(a) & static_cast<::std::uint32_t>(b));
    }
    constexpr TestBitflags2 operator^(TestBitflags2 a, TestBitflags2 b) noexcept {
        return static_cast<TestBitflags2>(static_cast<::std::uint32_t>(a) ^ static_cast<::std::uint32_t>(b));
    }
    constexpr TestBitflags2 operator~(TestBitflags2 a) noexcept {
        return static_cast<TestBitflags2>(~static_cast<::std::uint32_t>(a));
    }
    static_assert(sizeof(TestBitflags2) == 0x4);
} // namespace bitflags
