// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

#include "math.hpp"

namespace braced_imports {
    struct Transform;

    /// Transform type that uses imported Matrix4 and Vector3
    struct alignas(4) Transform {
        ::math::Matrix4 matrix;
        ::math::Vector3 position;
    };
    static_assert(sizeof(Transform) == 0x4C);
    static_assert(alignof(Transform) == 4);
} // namespace braced_imports
