// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace calling_conventions {
    struct Cc;

    struct alignas(4) Cc {
        ::std::uint32_t field;
        ::std::int32_t c_method(::std::int32_t x);
    };
    static_assert(sizeof(Cc) == 0x4);
    static_assert(alignof(Cc) == 4);

    using c_freestanding_t = ::std::int32_t (PYXIS_CDECL *)(::std::int32_t, ::std::int32_t);
    extern const c_freestanding_t c_freestanding;
} // namespace calling_conventions
