// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace cfg {
    struct CppOnlyType;
    struct Probe;

    struct alignas(4) CppOnlyType {
        ::std::uint32_t flag;
    };
    static_assert(sizeof(CppOnlyType) == 0x4);
    static_assert(alignof(CppOnlyType) == 4);

    struct alignas(4) Probe {
        ::std::uint32_t value;
        ::std::uint32_t read() const;
        ::std::uint32_t cpp_only() const;
        ::std::uint32_t cpp_or_json() const;
        ::std::uint32_t not_rust() const;
    };
    static_assert(sizeof(Probe) == 0x4);
    static_assert(alignof(Probe) == 4);


    inline ::std::uint32_t Probe::read() const { return value; }
    inline ::std::uint32_t Probe::cpp_only() const { return value + 2; }
    inline ::std::uint32_t Probe::cpp_or_json() const { return value + 3; }
    inline ::std::uint32_t Probe::not_rust() const { return value + 4; }
} // namespace cfg
