// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace consts {
    enum class AccessFlags : ::std::uint32_t;
    enum class Color : ::std::uint8_t;
    struct Player;

    enum class AccessFlags : ::std::uint32_t {
        READ = 0x1,
        WRITE = 0x2,
    };
    constexpr AccessFlags operator|(AccessFlags a, AccessFlags b) noexcept {
        return static_cast<AccessFlags>(static_cast<::std::uint32_t>(a) | static_cast<::std::uint32_t>(b));
    }
    constexpr AccessFlags operator&(AccessFlags a, AccessFlags b) noexcept {
        return static_cast<AccessFlags>(static_cast<::std::uint32_t>(a) & static_cast<::std::uint32_t>(b));
    }
    constexpr AccessFlags operator^(AccessFlags a, AccessFlags b) noexcept {
        return static_cast<AccessFlags>(static_cast<::std::uint32_t>(a) ^ static_cast<::std::uint32_t>(b));
    }
    constexpr AccessFlags operator~(AccessFlags a) noexcept {
        return static_cast<AccessFlags>(~static_cast<::std::uint32_t>(a));
    }
    static_assert(sizeof(AccessFlags) == 0x4);
    constexpr ::std::uint32_t AccessFlags_DEFAULT_MASK = 3;

    enum class Color : ::std::uint8_t {
        Red = 0,
        Green = 1,
        Blue = 2,
    };
    static_assert(sizeof(Color) == 0x1);
    constexpr Color Color_DEFAULT = Color::Red;

    constexpr Color DEFAULT_COLOR = Color::Red;

    constexpr const char* const GAME_NAME = "Pyxis";

    constexpr double GRAVITY = 9.81;

    constexpr ::std::int32_t MAX_HEALTH = 100;

    struct alignas(4) Player {
        ::std::int32_t health;

        static constexpr ::std::uint32_t STARTING_GOLD = 500;

        static constexpr float SPAWN_X = 0.0f;

        struct Inventory {
            ::std::uint32_t slots;
            static constexpr ::std::uint32_t MAX_SLOTS = 30;
        };
    };
    static_assert(sizeof(Player) == 0x4);
    static_assert(alignof(Player) == 4);

    constexpr float SCALE_FACTOR = 1.5f;
} // namespace consts
