// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace consts {
    enum class AccessFlags : ::std::uint32_t;
    enum class Color : ::std::uint8_t;
    struct Player;

    /// The permissive baseline is [`DEFAULT_MASK`](AccessFlags::DEFAULT_MASK).
    enum class AccessFlags : ::std::uint32_t {
        READ = 0x1,
        WRITE = 0x2,
    };
    constexpr AccessFlags operator|(AccessFlags a, AccessFlags b) noexcept {
        return static_cast<AccessFlags>(static_cast<::std::uint32_t>(a) | static_cast<::std::uint32_t>(b));
    }
    constexpr AccessFlags operator&(AccessFlags a, AccessFlags b) noexcept {
        return static_cast<AccessFlags>(static_cast<::std::uint32_t>(a) & static_cast<::std::uint32_t>(b));
    }
    constexpr AccessFlags operator^(AccessFlags a, AccessFlags b) noexcept {
        return static_cast<AccessFlags>(static_cast<::std::uint32_t>(a) ^ static_cast<::std::uint32_t>(b));
    }
    constexpr AccessFlags operator~(AccessFlags a) noexcept {
        return static_cast<AccessFlags>(~static_cast<::std::uint32_t>(a));
    }
    static_assert(sizeof(AccessFlags) == 0x4);
    constexpr ::std::uint32_t AccessFlags_DEFAULT_MASK = 3;

    /// Defaults to [`DEFAULT`](Color::DEFAULT).
    enum class Color : ::std::uint8_t {
        Red = 0,
        Green = 1,
        Blue = 2,
    };
    static_assert(sizeof(Color) == 0x1);
    constexpr Color Color_DEFAULT = Color::Red;

    struct alignas(4) Player {
        /// New players begin with [`STARTING_GOLD`](Player::STARTING_GOLD) gold,
        /// spawn at x=[`SPAWN_X`](Player::SPAWN_X), and can hold up to
        /// [`MAX_SLOTS`](Player::Inventory::MAX_SLOTS) items.
        ::std::int32_t health;

        static constexpr ::std::uint32_t STARTING_GOLD = 500;
        static constexpr float SPAWN_X = 0.0f;
        static const ::math::Matrix4 IDENTITY_MATRIX;
        static constexpr const char* const PLAYER_DLL = "player.dll";

        struct Inventory {
            ::std::uint32_t slots;

            static constexpr ::std::uint32_t MAX_SLOTS = 30;
        };
    };
    static_assert(sizeof(Player) == 0x4);
    static_assert(alignof(Player) == 4);
    inline const ::math::Matrix4 Player::IDENTITY_MATRIX = { { 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0 } };

    inline const ::math::Matrix4 IDENTITY = { { 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0 } };
    inline const ::math::Camera DEFAULT_CAMERA = { { 0.0, 0.0, 0.0 }, { { { 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0 } }, IDENTITY, { { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } } } };
    constexpr Color DEFAULT_COLOR = Color::Red;
    constexpr ::std::int32_t MAX_HEALTH = 100;
    inline const ::std::int32_t DEFAULT_HEALTH = MAX_HEALTH;
    constexpr const char* const DLL_NAME = "MSVCP80";
    inline const ::math::Vector3 EMPTY_VEC = { 0.0, 0.0, 0.0 };
    constexpr const char* const GAME_NAME = "Pyxis";
    constexpr double GRAVITY = 9.81;
    constexpr float SCALE_FACTOR = 1.5f;
    inline const ::math::Vector3 SPAWN_POINT = EMPTY_VEC;
    constexpr const char* const SYMBOL_NAME = "??0?$basic_string@D";
    inline const ::math::Matrix4 ZERO_MATRIX = { { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } };
} // namespace consts
