// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace definition_body {
    struct Logger;

    struct alignas(4) Logger {
        ::std::uint32_t seen;
        static Logger make();
        ::std::uint32_t record();
    };
    static_assert(sizeof(Logger) == 0x4);
    static_assert(alignof(Logger) == 4);
} // namespace definition_body
