// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace diamond_inheritance {
    struct Base;
    struct BaseA;
    struct BaseAVftable;
    struct BaseB;
    struct BaseBVftable;
    struct BaseVftable;
    struct Derived;
    struct DerivedVftable;

    struct alignas(8) Base {
        const BaseVftable* vftable;

        const BaseVftable* _vftable_ptr() const;
        void destructor();
    };
    static_assert(sizeof(Base) == 0x8);
    static_assert(alignof(Base) == 8);

    struct alignas(8) BaseA {
        Base base;

        operator Base&() { return this->base; }
        operator const Base&() const { return this->base; }

        const BaseAVftable* _vftable_ptr() const;
        void destructor();
        void associated();
    };
    static_assert(sizeof(BaseA) == 0x8);
    static_assert(alignof(BaseA) == 8);

    struct alignas(8) BaseAVftable {
        void (*destructor)(void*);
    };
    static_assert(sizeof(BaseAVftable) == 0x8);
    static_assert(alignof(BaseAVftable) == 8);

    struct alignas(8) BaseB {
        Base base;

        operator Base&() { return this->base; }
        operator const Base&() const { return this->base; }

        const BaseBVftable* _vftable_ptr() const;
        void destructor();
        void associated();
    };
    static_assert(sizeof(BaseB) == 0x8);
    static_assert(alignof(BaseB) == 8);

    struct alignas(8) BaseBVftable {
        void (*destructor)(void*);
    };
    static_assert(sizeof(BaseBVftable) == 0x8);
    static_assert(alignof(BaseBVftable) == 8);

    struct alignas(8) BaseVftable {
        void (*destructor)(void*);
    };
    static_assert(sizeof(BaseVftable) == 0x8);
    static_assert(alignof(BaseVftable) == 8);

    struct alignas(8) Derived {
        BaseA base_a;
        BaseB base_b;

        operator BaseA&() { return this->base_a; }
        operator const BaseA&() const { return this->base_a; }

        operator BaseB&() { return this->base_b; }
        operator const BaseB&() const { return this->base_b; }

        const DerivedVftable* _vftable_ptr() const;
        void destructor();
        void associated();
        void base_b_associated();
        void base_b_destructor();
    };
    static_assert(sizeof(Derived) == 0x10);
    static_assert(alignof(Derived) == 8);

    struct alignas(8) DerivedVftable {
        void (*destructor)(void*);
    };
    static_assert(sizeof(DerivedVftable) == 0x8);
    static_assert(alignof(DerivedVftable) == 8);

    inline const BaseVftable* Base::_vftable_ptr() const { return this->vftable; }
    inline void Base::destructor() {
        _vftable_ptr()->destructor(this);
    }
    inline const BaseAVftable* BaseA::_vftable_ptr() const { return reinterpret_cast<const BaseAVftable*>(this->base._vftable_ptr()); }
    inline void BaseA::destructor() {
        _vftable_ptr()->destructor(this);
    }
    inline void BaseA::associated() {
        using fn_t = void (*)(void*);
        reinterpret_cast<fn_t>(0x123)(this);
    }
    inline const BaseBVftable* BaseB::_vftable_ptr() const { return reinterpret_cast<const BaseBVftable*>(this->base._vftable_ptr()); }
    inline void BaseB::destructor() {
        _vftable_ptr()->destructor(this);
    }
    inline void BaseB::associated() {
        using fn_t = void (*)(void*);
        reinterpret_cast<fn_t>(0x123)(this);
    }
    inline const DerivedVftable* Derived::_vftable_ptr() const { return reinterpret_cast<const DerivedVftable*>(this->base_a._vftable_ptr()); }
    inline void Derived::destructor() {
        _vftable_ptr()->destructor(this);
    }
    inline void Derived::associated() {
        this->base_a.associated();
    }
    inline void Derived::base_b_associated() {
        this->base_b.associated();
    }
    inline void Derived::base_b_destructor() {
        this->base_b.destructor();
    }
} // namespace diamond_inheritance
