// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace doc_comments {
    struct TestType;
    struct TestTypeVftable;

    /// This is a doc comment
    struct alignas(8) TestType {
        const TestTypeVftable* vftable;
        /// This is a field doc comment
        ::std::uint64_t field_1;

        const TestTypeVftable* _vftable_ptr() const;
        /// My test vfunc!
        void test_vfunc() const;
        /// My test func!
        ///
        /// And its second line! :)
        void test_func() const;
    };
    static_assert(sizeof(TestType) == 0x10);
    static_assert(alignof(TestType) == 8);

    struct alignas(8) TestTypeVftable {
        /// My test vfunc!
        void (*test_vfunc)(const void*);
    };
    static_assert(sizeof(TestTypeVftable) == 0x8);
    static_assert(alignof(TestTypeVftable) == 8);
} // namespace doc_comments
