// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace doc_self_links {
    struct Container;
    struct VirtualContainer;
    struct VirtualContainerVftable;

    /// Test `Self::` links in type docs.
    ///
    /// Link to a field as [`Self::field`](@ref doc_self_links::Container::field), to a method as
    /// [`Self::method`](@ref doc_self_links::Container::method), to a nested type as
    /// [`Self::Nested`](@ref doc_self_links::Container::Nested), and to a nested type's member as
    /// [`Self::Nested::nested_field`](@ref doc_self_links::Container::Nested::nested_field).
    struct alignas(4) Container {
        /// A nested type. Its field is [`Self::nested_field`](@ref doc_self_links::Container::Nested::nested_field).
        struct Nested {
            ::std::uint16_t nested_field;
        };
        /// A field.
        ::std::uint32_t field;
        /// A method.
        void method() const;
    };
    static_assert(sizeof(Container) == 0x4);
    static_assert(alignof(Container) == 4);

    /// Test `Self::` links written in vftable-function docs. Those docs are
    /// copied onto the generated `VirtualContainerVftable`'s function-pointer
    /// fields, where `Self` must still mean the declaring type — not the
    /// generated vftable struct.
    struct alignas(8) VirtualContainer {
        const VirtualContainerVftable* vftable;
        /// A field a vftable-function doc links to via `Self::`.
        ::std::uint32_t counter;
        ::std::uint32_t padding;

        const VirtualContainerVftable* _vftable_ptr() const;
        /// Reads [`counter`](@ref doc_self_links::VirtualContainer::counter) and calls
        /// [`get_counter`](@ref doc_self_links::VirtualContainer::get_counter).
        ::std::uint32_t get_counter() const;
    };
    static_assert(sizeof(VirtualContainer) == 0x10);
    static_assert(alignof(VirtualContainer) == 8);

    struct alignas(8) VirtualContainerVftable {
        /// Reads [`counter`](@ref doc_self_links::VirtualContainer::counter) and calls
        /// [`get_counter`](@ref doc_self_links::VirtualContainer::get_counter).
        ::std::uint32_t (*get_counter)(const void*);
    };
    static_assert(sizeof(VirtualContainerVftable) == 0x8);
    static_assert(alignof(VirtualContainerVftable) == 8);
} // namespace doc_self_links
