// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace doc_self_links {
    struct Container;

    /// Test `Self::` links in type docs.
    ///
    /// Link to a field as [`Self::field`](@ref doc_self_links::Container::field), to a method as
    /// [`Self::method`](@ref doc_self_links::Container::method), to a nested type as
    /// [`Self::Nested`](@ref doc_self_links::Container::Nested), and to a nested type's member as
    /// [`Self::Nested::nested_field`](@ref doc_self_links::Container::Nested::nested_field).
    struct alignas(4) Container {
        /// A field.
        ::std::uint32_t field;
        /// A method.
        void method() const;

        /// A nested type. Its field is [`Self::nested_field`](@ref doc_self_links::Container::Nested::nested_field).
        struct Nested {
            ::std::uint16_t nested_field;
        };
    };
    static_assert(sizeof(Container) == 0x4);
    static_assert(alignof(Container) == 4);
} // namespace doc_self_links
