// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace enums {
    enum class TestEnum : ::std::uint32_t {
        None = 0,
        Some = 1,
        Value = 2,
    };
    static_assert(sizeof(TestEnum) == 0x4);
} // namespace enums
