// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace external_body {
    struct Counter;
    template <class T> struct Pair;

    template <class T>
    struct Pair {
        T* first;
        T* second;
        T* first_ptr() const;
        template <class Y>
        Y* cast_first() const;
    };

    struct alignas(4) Counter {
        ::std::uint32_t value;
        static Counter make();
        ::std::uint32_t bump();
        ::std::uint32_t read() const;
    };
    static_assert(sizeof(Counter) == 0x4);
    static_assert(alignof(Counter) == 4);

    ::std::uint32_t module_hello();

    inline Counter Counter::make() { return Counter{0}; }
    inline ::std::uint32_t Counter::bump() { value += 1; return value; }
    inline ::std::uint32_t Counter::read() const { return value; }
    inline ::std::uint32_t module_hello() { return 42; }
    template <class T>
    inline T* Pair<T>::first_ptr() const { return first; }

    template <class T> template <class Y>
    inline Y* Pair<T>::cast_first() const { return reinterpret_cast<Y*>(first); }
} // namespace external_body
