// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace external_body {
    struct Counter;

    struct alignas(4) Counter {
        ::std::uint32_t value;
        Counter make();
        ::std::uint32_t bump();
        ::std::uint32_t read() const;
    };
    static_assert(sizeof(Counter) == 0x4);
    static_assert(alignof(Counter) == 4);

    ::std::uint32_t module_hello();


    inline Counter Counter::make() { return Counter{0}; }
    inline ::std::uint32_t Counter::bump() { value += 1; return value; }
    inline ::std::uint32_t Counter::read() const { return value; }


    inline ::std::uint32_t module_hello() { return 42; }
} // namespace external_body
