// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace extern_bindings {
    struct UsesAtomicHandle;

    struct alignas(4) UsesAtomicHandle {
        ::std::atomic<::std::uint32_t> handle;
    };
    static_assert(sizeof(UsesAtomicHandle) == 0x4);
    static_assert(alignof(UsesAtomicHandle) == 4);
} // namespace extern_bindings
