// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace extern_values {
    enum class DebugFlags : ::std::uint32_t;
    enum class RenderMode : ::std::uint8_t;
    struct Engine;

    /// The active flag set is [`g_active`](DebugFlags::g_active).
    enum class DebugFlags : ::std::uint32_t {
        WIREFRAME = 0x1,
        OVERDRAW = 0x2,
    };
    constexpr DebugFlags operator|(DebugFlags a, DebugFlags b) noexcept {
        return static_cast<DebugFlags>(static_cast<::std::uint32_t>(a) | static_cast<::std::uint32_t>(b));
    }
    constexpr DebugFlags operator&(DebugFlags a, DebugFlags b) noexcept {
        return static_cast<DebugFlags>(static_cast<::std::uint32_t>(a) & static_cast<::std::uint32_t>(b));
    }
    constexpr DebugFlags operator^(DebugFlags a, DebugFlags b) noexcept {
        return static_cast<DebugFlags>(static_cast<::std::uint32_t>(a) ^ static_cast<::std::uint32_t>(b));
    }
    constexpr DebugFlags operator~(DebugFlags a) noexcept {
        return static_cast<DebugFlags>(~static_cast<::std::uint32_t>(a));
    }
    static_assert(sizeof(DebugFlags) == 0x4);
    DebugFlags*& DebugFlags_get_g_active();

    struct alignas(4) Engine {
        /// The live instance is [`g_instance`](Engine::g_instance).
        ::std::uint32_t frame;

        static Engine*& get_g_instance();
    };
    static_assert(sizeof(Engine) == 0x4);
    static_assert(alignof(Engine) == 4);

    /// The active mode is [`g_current`](RenderMode::g_current).
    enum class RenderMode : ::std::uint8_t {
        Forward = 0,
        Deferred = 1,
    };
    static_assert(sizeof(RenderMode) == 0x1);
    RenderMode*& RenderMode_get_g_current();

    /// The engine singleton, of type [`Engine`]. Advances with [`g_frame_count`].
    Engine*& get_g_engine();

    ::std::uint32_t& get_g_frame_count();
} // namespace extern_values
