// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace field_type_name_collision {
    struct MovieImpl;
    struct Viewport;

    struct alignas(8) Viewport {
        ::std::uint32_t width;
        ::std::uint32_t height;
    };
    static_assert(sizeof(Viewport) == 0x8);
    static_assert(alignof(Viewport) == 8);

    struct alignas(8) MovieImpl {
        ::field_type_name_collision::Viewport Viewport;
        void set_viewport(const ::field_type_name_collision::Viewport* desc);
    };
    static_assert(sizeof(MovieImpl) == 0x8);
    static_assert(alignof(MovieImpl) == 8);
} // namespace field_type_name_collision
