// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace freestanding_functions {
    enum class A : ::std::int32_t;

    enum class A : ::std::int32_t {
        None = 0,
    };
    static_assert(sizeof(A) == 0x4);

    /// A freestanding function with a doc comment.
    ///
    /// And a second line, for good measure.
    using freestanding_t = void (*)();
    extern const freestanding_t freestanding;
} // namespace freestanding_functions
