// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace function_pointers {
    struct Callbacks;
    struct Engine;

    /// Callback slots. Nothing here is a vftable: the struct simply holds raw
    /// function pointers the target installs itself.
    struct alignas(8) Callbacks {
        /// Named parameters, default calling convention.
        void (*on_tick)(Engine*, float);
        /// Parameters may be left unnamed, and the signature can return a value.
        bool (*on_event)(Engine*, ::std::uint32_t);
        /// A no-argument slot.
        void (*on_shutdown)();
        /// The convention is selected by an attribute on the type itself, so it
        /// works in nested positions too.
        Engine* (PYXIS_CDECL *on_alloc)(::std::uint32_t);
        /// A dispatch table: an array of function pointers, each with its own
        /// convention.
        void (PYXIS_CDECL *table[4])(Engine*);
        /// Via the alias.
        void (*aliased)(Engine*, float);
        /// Pointer-to-function-pointer, for a slot the target rewrites in place.
        void (**indirect)(Engine*);
        /// A signature that itself takes a callback.
        void (*on_register)(void (*)(Engine*), Engine*);
        /// A pointer to a const function-pointer slot. `const` qualifies the
        /// pointee, so it must land on the inner `*` in C++ (`void (*const *)()`),
        /// not on the return type.
        void (*const *locked)(Engine*);
        /// `_` is a parameter name, as it is in field position.
        void (*on_ignore)(::std::uint32_t);
        /// Function pointers work in argument and return position too.
        void (*install(void (*tick)(Engine*, float)))(Engine*, float);
        /// An array parameter has to render identically in the declaration and in
        /// the function-pointer alias the body calls through, or the two disagree
        /// and the emitted C++ doesn't compile.
        void seed(::std::uint32_t values[4]);
    };
    static_assert(sizeof(Callbacks) == 0x68);
    static_assert(alignof(Callbacks) == 8);

    /// The engine a callback is handed a pointer to.
    struct alignas(4) Engine {
        ::std::uint32_t frame;
    };
    static_assert(sizeof(Engine) == 0x4);
    static_assert(alignof(Engine) == 4);

    /// A named signature, reused below. A function-pointer type is an ordinary
    /// type, so it aliases like any other.
    using TickFn = void (*)(Engine*, float);
} // namespace function_pointers
