// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace function_pointer_nesting {
    struct Ctx;
    struct Dispatch;
    struct DispatchVftable;
    struct Nested;
    struct ShimNames;
    struct ShimNamesVftable;
    template <class T> struct Slot;
    union HookSlot;

    /// A generic instantiated with a function pointer, exercising the type in
    /// template-argument position. Sized explicitly, as any generic whose layout
    /// can't be computed from its parameters must be.
    template <class T>
    struct Slot {
        T* value;
    };

    /// Passed around by pointer as the callback context.
    struct alignas(8) Ctx {
        ::std::uint64_t id;
    };
    static_assert(sizeof(Ctx) == 0x8);
    static_assert(alignof(Ctx) == 8);

    /// Function pointers in vftable slots, in both argument and return position.
    struct alignas(8) Dispatch {
        const DispatchVftable* vftable;

        const DispatchVftable* _vftable_ptr() const;
        void (*install(bool (*cb)(Ctx*)))(Ctx*);
        void (*(*table() const)[4])();
    };
    static_assert(sizeof(Dispatch) == 0x8);
    static_assert(alignof(Dispatch) == 8);

    struct alignas(8) DispatchVftable {
        void (*(*install)(void*, bool (*)(Ctx*)))(Ctx*);
        void (*(*(*table)(const void*))[4])();
    };
    static_assert(sizeof(DispatchVftable) == 0x10);
    static_assert(alignof(DispatchVftable) == 8);

    /// A signature that itself takes and returns signatures, reached through an
    /// alias to check aliases carry the whole nested type.
    using Handler = void (*(*)(bool (*)(Ctx*)))(Ctx*);

    /// A union whose members are competing readings of one pointer-sized slot.
    union alignas(8) HookSlot {
        bool (*as_fn)(Ctx*);
        ::std::uint64_t as_address;
    };
    static_assert(sizeof(HookSlot) == 0x8);
    static_assert(alignof(HookSlot) == 8);

    struct alignas(8) Nested {
        /// Three levels of parameter nesting.
        ::std::uint32_t (*three)(::std::uint32_t (*)(::std::uint32_t (*)(Ctx*)));
        /// Three levels of return nesting, the hardest C++ declarator shape here.
        /// Doxygen mis-parses it (see DOXYGEN_IGNORED_WARNINGS in test.py); clang
        /// and gcc accept it, and this corpus compiles its own output.
        bool (*(*(*curried)(Ctx*))(::std::uint32_t))();
        /// An array of arrays of function pointers.
        void (*grid[3][2])(Ctx*);
        /// A pointer to an array of function pointers. In C++ the subscript binds
        /// tighter than the star, so this needs parens where an array of pointers
        /// does not.
        void (*(*table_ptr)[4])(Ctx*);
        /// A const pointer to a function pointer: the qualifier belongs to the
        /// pointee, not to the return type.
        void (*const *locked)(Ctx*);
        /// An array by value alongside a pointer to a function pointer.
        void (*bulk)(::std::uint32_t [4], void (**)(::std::uint32_t));
        /// A convention on the outer type only. The parameter and the return
        /// type must keep the default, not inherit it - so each of the three
        /// positions is exercised alone, with the other two left default.
        void (*(PYXIS_CDECL *cc_outer)(bool (*)(::std::uint32_t)))();
        /// The same, on the return type only.
        void (PYXIS_CDECL *(*cc_return)(bool (*)(::std::uint32_t)))();
        /// The same, on the parameter only.
        void (*(*cc_param)(bool (PYXIS_CDECL *)(::std::uint32_t)))();
        /// All three annotated at once, so the attributes have to coexist in a
        /// single type expression rather than one per field. The parameter takes
        /// the other convention, so an outer one reaching it would still show.
        void (PYXIS_CDECL *(PYXIS_CDECL *cc_all)(bool (*)(::std::uint32_t)))();
        /// Structs passed and returned by value through a function pointer. The
        /// parameter is the enclosing module's type, not a pointer to it.
        Ctx (*by_value)(Ctx);
        /// The alias above, which is itself a nested signature.
        void (*(*aliased)(bool (*)(Ctx*)))(Ctx*);
        /// A function pointer as a generic argument.
        Slot<bool (*)(Ctx*)> slot;
    };
    static_assert(sizeof(Nested) == 0x90);
    static_assert(alignof(Nested) == 8);

    /// Parameters named after the locals the generated call shims used to bind.
    /// The Rust backend called the target through a local `f`, which a parameter
    /// of the same name shadowed - the shim passed itself instead of the argument.
    /// Both the `#[address]` and vftable shims are covered.
    struct alignas(8) ShimNames {
        const ShimNamesVftable* vftable;

        const ShimNamesVftable* _vftable_ptr() const;
        Ctx* via_vftable(Ctx* f, ::std::uint32_t this_);
        void (*via_address(void (*f)(Ctx*), ::std::uint32_t this_))(Ctx*);
    };
    static_assert(sizeof(ShimNames) == 0x8);
    static_assert(alignof(ShimNames) == 8);

    struct alignas(8) ShimNamesVftable {
        Ctx* (*via_vftable)(void*, Ctx*, ::std::uint32_t);
    };
    static_assert(sizeof(ShimNamesVftable) == 0x8);
    static_assert(alignof(ShimNamesVftable) == 8);

    /// A global function pointer at a fixed address.
    bool (*&get_g_hook())(Ctx*);
} // namespace function_pointer_nesting
