// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

#include "generics.hpp"

namespace generics_cross_module {
    struct Entity;
    struct EntityMap;
    struct NestedShared;
    struct SharedEntity;
    struct WeakEntity;

    /// Entity type for testing
    struct alignas(8) Entity {
        ::std::uint32_t id;
        ::std::uint32_t flags;
    };
    static_assert(sizeof(Entity) == 0x8);
    static_assert(alignof(Entity) == 8);

    /// Uses MapEntry<K, V> from another module
    struct alignas(8) EntityMap {
        ::generics::MapEntry<::std::uint32_t, Entity> entry;
    };
    static_assert(sizeof(EntityMap) == 0x10);
    static_assert(alignof(EntityMap) == 8);

    /// Nested generic from another module
    struct alignas(8) NestedShared {
        ::generics::Shared<::generics::Shared<Entity>> shared;
    };
    static_assert(sizeof(NestedShared) == 0x8);
    static_assert(alignof(NestedShared) == 8);

    /// Uses Shared<T> from another module with a local type
    struct alignas(8) SharedEntity {
        ::generics::Shared<Entity> shared;
    };
    static_assert(sizeof(SharedEntity) == 0x8);
    static_assert(alignof(SharedEntity) == 8);

    /// Uses WeakPtr<T> from another module
    struct alignas(8) WeakEntity {
        ::generics::WeakPtr<Entity> weak;
    };
    static_assert(sizeof(WeakEntity) == 0x8);
    static_assert(alignof(WeakEntity) == 8);
} // namespace generics_cross_module
