// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace math {
    struct Matrix4;
    struct Vector3;

    /// 4x4 matrix type for transformations
    struct alignas(4) Matrix4 {
        float data[16];
    };
    static_assert(sizeof(Matrix4) == 0x40);
    static_assert(alignof(Matrix4) == 4);

    /// 3D vector type
    struct alignas(4) Vector3 {
        float x;
        float y;
        float z;
    };
    static_assert(sizeof(Vector3) == 0xC);
    static_assert(alignof(Vector3) == 4);
} // namespace math
