// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace math {
    struct Matrix4;
    struct Vector3;
    struct VectorGrid;

    /// 4x4 matrix type for transformations
    struct alignas(4) Matrix4 {
        float data[16];
    };
    static_assert(sizeof(Matrix4) == 0x40);
    static_assert(alignof(Matrix4) == 4);

    /// 3D vector type
    struct alignas(4) Vector3 {
        float x;
        float y;
        float z;
    };
    static_assert(sizeof(Vector3) == 0xC);
    static_assert(alignof(Vector3) == 4);

    /// Nested array type: a 3D grid of vectors indexed as `cells[z][y][x]`.
    struct alignas(4) VectorGrid {
        Vector3 cells[2][3][4];
    };
    static_assert(sizeof(VectorGrid) == 0x120);
    static_assert(alignof(VectorGrid) == 4);
} // namespace math
