// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace member_named_after_type {
    struct Catalogue;
    struct Counter;
    struct Dispatcher;
    struct DispatcherVftable;
    struct Registry;
    struct Station;
    struct Teleporter;
    union Choice;

    /// A type with a nested type named after it, referenced by a field.
    struct alignas(8) Catalogue {
        /// A nested type named after its enclosing type. Its field is
        /// [`Catalogue::Catalogue::entries`](@ref member_named_after_type::Catalogue::Catalogue_::entries).
        struct Catalogue_ {
            ::std::uint32_t entries;
        };

        /// Nested bitflags with a flag named after them:
        /// [`Shelf::Shelf`](@ref member_named_after_type::Catalogue::Shelf::Shelf_).
        struct Shelf {
            static constexpr ::std::uint32_t Shelf_ = 1;
            static constexpr ::std::uint32_t Other = 2;
        };

        /// A nested enum with a variant named after it:
        /// [`Kind::Kind`](@ref member_named_after_type::Catalogue::Kind::Kind).
        enum class Kind : ::std::uint32_t {
            Kind = 0,
            Other = 1,
        };
        ::member_named_after_type::Catalogue::Catalogue_ inner;
        ::member_named_after_type::Catalogue::Shelf shelf;
        ::member_named_after_type::Catalogue::Kind kind;
        ::std::uint32_t reserved;
    };
    static_assert(sizeof(Catalogue) == 0x10);
    static_assert(alignof(Catalogue) == 8);

    /// A union with a member named after it: [`Choice::Choice`](@ref member_named_after_type::Choice::Choice_).
    union alignas(4) Choice {
        ::std::uint32_t Choice_;
        float other;
    };
    static_assert(sizeof(Choice) == 0x4);
    static_assert(alignof(Choice) == 4);

    /// A pinned type with a field named after it: [`Counter::Counter`](@ref member_named_after_type::Counter::Counter_).
    struct alignas(4) Counter {
        ::std::uint32_t Counter_;

        Counter(const Counter&) = delete;
        Counter(Counter&&) = delete;
        Counter& operator=(const Counter&) = delete;
        Counter& operator=(Counter&&) = delete;
    };
    static_assert(sizeof(Counter) == 0x4);
    static_assert(alignof(Counter) == 4);

    /// A type with a vftable function named after it:
    /// [`Dispatcher::Dispatcher`](@ref member_named_after_type::Dispatcher::Dispatcher_).
    struct alignas(8) Dispatcher {
        const DispatcherVftable* vftable;

        const DispatcherVftable* _vftable_ptr() const;
        ::std::uint32_t Dispatcher_(::std::uint32_t value);
    };
    static_assert(sizeof(Dispatcher) == 0x8);
    static_assert(alignof(Dispatcher) == 8);

    struct alignas(8) DispatcherVftable {
        ::std::uint32_t (*Dispatcher)(void*, ::std::uint32_t);
    };
    static_assert(sizeof(DispatcherVftable) == 0x8);
    static_assert(alignof(DispatcherVftable) == 8);

    /// A type whose nested items are named after it: [`Registry::Registry`](@ref member_named_after_type::Registry::Registry_) is a
    /// constant, and [`Catalogue::Catalogue`](@ref member_named_after_type::Catalogue::Catalogue_) is a nested type.
    struct alignas(4) Registry {
        ::std::uint32_t size;

        /// A nested constant named after its enclosing type.
        static constexpr ::std::uint32_t Registry_ = 7;
    };
    static_assert(sizeof(Registry) == 0x4);
    static_assert(alignof(Registry) == 4);

    /// A type with a method named after it: [`Teleporter::Teleporter`](@ref member_named_after_type::Teleporter::Teleporter_).
    struct alignas(4) Teleporter {
        ::std::uint32_t state;
        /// Teleports.
        bool Teleporter_();
    };
    static_assert(sizeof(Teleporter) == 0x4);
    static_assert(alignof(Teleporter) == 4);

    /// A type that forwards [`Teleporter::Teleporter`](@ref member_named_after_type::Teleporter::Teleporter_) through its base field
    /// [`Station::base`](@ref member_named_after_type::Station::base).
    struct alignas(4) Station {
        ::member_named_after_type::Teleporter base;

        operator ::member_named_after_type::Teleporter&() { return this->base; }
        operator const ::member_named_after_type::Teleporter&() const { return this->base; }
        /// Teleports.
        bool Teleporter();
    };
    static_assert(sizeof(Station) == 0x4);
    static_assert(alignof(Station) == 4);
} // namespace member_named_after_type
