// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace min_size {
    struct RoundedType;
    struct TestType;

    /// Another type to test min_size rounding
    struct alignas(16) RoundedType {
        ::std::uint64_t value;
        ::std::uint8_t _field_8[24];
    };
    static_assert(sizeof(RoundedType) == 0x20);
    static_assert(alignof(RoundedType) == 16);

    /// Test type with min_size attribute
    struct alignas(16) TestType {
        ::std::int32_t field_1;
        ::std::int32_t field_2;
        ::std::uint8_t _field_8[24];
    };
    static_assert(sizeof(TestType) == 0x20);
    static_assert(alignof(TestType) == 16);
} // namespace min_size
