// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace multiple_levels {
    struct Base;
    struct BaseVftable;
    struct Derived;
    struct DerivedDerived;
    struct DerivedDerivedDerived;
    struct DerivedDerivedDerivedVftable;
    struct DerivedDerivedVftable;
    struct DerivedVftable;

    struct alignas(8) Base {
        const BaseVftable* vftable;
        ::std::uint64_t base_field;

        const BaseVftable* _vftable_ptr() const;
        ::std::int32_t base_vfunc(::std::int32_t a) const;
        ::std::int32_t base_associated(::std::int32_t a) const;
    };
    static_assert(sizeof(Base) == 0x10);
    static_assert(alignof(Base) == 8);

    struct alignas(8) BaseVftable {
        ::std::int32_t (*base_vfunc)(const void*, ::std::int32_t);
    };
    static_assert(sizeof(BaseVftable) == 0x8);
    static_assert(alignof(BaseVftable) == 8);

    struct alignas(8) Derived {
        Base base;
        ::std::uint64_t derived_field;

        operator Base&() { return this->base; }
        operator const Base&() const { return this->base; }

        const DerivedVftable* _vftable_ptr() const;
        ::std::int32_t base_vfunc(::std::int32_t a) const;
        ::std::int32_t derived_vfunc(::std::int32_t a) const;
        ::std::int32_t base_associated(::std::int32_t a) const;
        ::std::int32_t derived_associated(::std::int32_t a) const;
    };
    static_assert(sizeof(Derived) == 0x18);
    static_assert(alignof(Derived) == 8);

    struct alignas(8) DerivedDerived {
        Derived derived;
        ::std::uint64_t derived_derived_field;

        operator Derived&() { return this->derived; }
        operator const Derived&() const { return this->derived; }

        const DerivedDerivedVftable* _vftable_ptr() const;
        ::std::int32_t base_vfunc(::std::int32_t a) const;
        ::std::int32_t derived_vfunc(::std::int32_t a) const;
        ::std::int32_t derived_derived_vfunc(::std::int32_t a) const;
        ::std::int32_t base_associated(::std::int32_t a) const;
        ::std::int32_t derived_associated(::std::int32_t a) const;
        ::std::int32_t derived_derived_associated(::std::int32_t a) const;
    };
    static_assert(sizeof(DerivedDerived) == 0x20);
    static_assert(alignof(DerivedDerived) == 8);

    struct alignas(8) DerivedDerivedDerived {
        DerivedDerived derived_derived;
        ::std::uint64_t derived_derived_derived_field;

        operator DerivedDerived&() { return this->derived_derived; }
        operator const DerivedDerived&() const { return this->derived_derived; }

        const DerivedDerivedDerivedVftable* _vftable_ptr() const;
        ::std::int32_t base_vfunc(::std::int32_t a) const;
        ::std::int32_t derived_vfunc(::std::int32_t a) const;
        ::std::int32_t derived_derived_vfunc(::std::int32_t a) const;
        ::std::int32_t derived_derived_derived_vfunc(::std::int32_t a) const;
        ::std::int32_t base_associated(::std::int32_t a) const;
        ::std::int32_t derived_associated(::std::int32_t a) const;
        ::std::int32_t derived_derived_associated(::std::int32_t a) const;
        ::std::int32_t derived_derived_derived_associated(::std::int32_t a) const;
    };
    static_assert(sizeof(DerivedDerivedDerived) == 0x28);
    static_assert(alignof(DerivedDerivedDerived) == 8);

    struct alignas(8) DerivedDerivedDerivedVftable {
        ::std::int32_t (*base_vfunc)(const void*, ::std::int32_t);
        ::std::int32_t (*derived_vfunc)(const void*, ::std::int32_t);
        ::std::int32_t (*derived_derived_vfunc)(const void*, ::std::int32_t);
        ::std::int32_t (*derived_derived_derived_vfunc)(const void*, ::std::int32_t);
    };
    static_assert(sizeof(DerivedDerivedDerivedVftable) == 0x20);
    static_assert(alignof(DerivedDerivedDerivedVftable) == 8);

    struct alignas(8) DerivedDerivedVftable {
        ::std::int32_t (*base_vfunc)(const void*, ::std::int32_t);
        ::std::int32_t (*derived_vfunc)(const void*, ::std::int32_t);
        ::std::int32_t (*derived_derived_vfunc)(const void*, ::std::int32_t);
    };
    static_assert(sizeof(DerivedDerivedVftable) == 0x18);
    static_assert(alignof(DerivedDerivedVftable) == 8);

    struct alignas(8) DerivedVftable {
        ::std::int32_t (*base_vfunc)(const void*, ::std::int32_t);
        ::std::int32_t (*derived_vfunc)(const void*, ::std::int32_t);
    };
    static_assert(sizeof(DerivedVftable) == 0x10);
    static_assert(alignof(DerivedVftable) == 8);
} // namespace multiple_levels
