// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace nested_items {
    struct Outer;

    /// A type with nested declarations.
    ///
    /// See [`InnerEnum`], [`InnerType`], [`InnerFlags`], and [`InnerAlias`].
    ///
    /// You can also qualify them: [`Outer::InnerEnum`], [`Outer::InnerType`].
    struct alignas(4) Outer {
        ::std::uint32_t field;

        /// An enum nested inside [`Outer`].
        ///
        /// Variants: [`InnerEnum::A`], [`InnerEnum::B`], [`InnerEnum::C`].
        enum class InnerEnum : ::std::uint8_t {
            A = 0,
            B = 1,
            C = 2,
        };

        /// A type nested inside [`Outer`].
        ///
        /// Its field is [`InnerType::inner_field`].
        struct InnerType {
            ::std::uint16_t inner_field;
        };

        /// Bitflags nested inside [`Outer`].
        ///
        /// Members: [`InnerFlags::FLAG_A`], [`InnerFlags::FLAG_B`].
        struct InnerFlags {
            static constexpr ::std::uint32_t FLAG_A = 1;
            static constexpr ::std::uint32_t FLAG_B = 2;
        };

        /// A type alias nested inside [`Outer`].
        using InnerAlias = ::std::uint32_t;
    };
    static_assert(sizeof(Outer) == 0x4);
    static_assert(alignof(Outer) == 4);
} // namespace nested_items
