// @generated by pyxis — do not edit
#pragma once

#include <atomic>
#include <cstdint>

// Calling-convention shim. We always target MSVC ABI (x86 32-bit Windows via
// clang-cl + xwin); on non-MSVC dev hosts the macros expand to nothing so
// generated headers still compile-check during iteration.
#if defined(_MSC_VER)
#  define PYXIS_CDECL __cdecl
#  define PYXIS_STDCALL __stdcall
#  define PYXIS_FASTCALL __fastcall
#  define PYXIS_THISCALL __thiscall
#  define PYXIS_VECTORCALL __vectorcall
#elif (defined(__i386__) || defined(_M_IX86)) && (defined(__GNUC__) || defined(__clang__))
#  define PYXIS_CDECL __attribute__((cdecl))
#  define PYXIS_STDCALL __attribute__((stdcall))
#  define PYXIS_FASTCALL __attribute__((fastcall))
#  define PYXIS_THISCALL __attribute__((thiscall))
#  define PYXIS_VECTORCALL __attribute__((sysv_abi))
#else
#  define PYXIS_CDECL
#  define PYXIS_STDCALL
#  define PYXIS_FASTCALL
#  define PYXIS_THISCALL
#  define PYXIS_VECTORCALL
#endif

namespace pyxis {
// Atomic primitives map to `std::atomic<T>`. On every reasonable platform
// these specialise to the same size and alignment as the underlying integer
// (so the layout `static_assert`s pyxis emits hold), and they give real
// load/store/CAS semantics for projects that need them (e.g. JC2's
// SharedPtr refcount logic).
using AtomicBool = ::std::atomic<bool>;
using AtomicU8   = ::std::atomic<::std::uint8_t>;
using AtomicU16  = ::std::atomic<::std::uint16_t>;
using AtomicU32  = ::std::atomic<::std::uint32_t>;
using AtomicU64  = ::std::atomic<::std::uint64_t>;
using AtomicI8   = ::std::atomic<::std::int8_t>;
using AtomicI16  = ::std::atomic<::std::int16_t>;
using AtomicI32  = ::std::atomic<::std::int32_t>;
using AtomicI64  = ::std::atomic<::std::int64_t>;

// Wrapper that suppresses `T`'s destructor (mirrors Rust's
// `core::mem::ManuallyDrop<T>`). Same layout as T; the inner value lives in
// a union, so when a `ManuallyDrop<T>` goes out of scope, *nothing* runs on
// `value` — to destroy it you must call `md.value.~T()` explicitly. The
// default constructor leaves `value` uninitialised, again matching Rust's
// ManuallyDrop semantics for fields within zero-initialised parents.
template <class T>
union ManuallyDrop {
    T value;
    ManuallyDrop() {}
    ~ManuallyDrop() {}
};
} // namespace pyxis
