// @generated by pyxis — do not edit
#pragma once

#include <cstdint>

// Calling-convention shim. We always target MSVC ABI (x86 32-bit Windows via
// clang-cl + xwin); on non-MSVC dev hosts the macros expand to nothing so
// generated headers still compile-check during iteration.
#if defined(_MSC_VER)
#  define PYXIS_CDECL __cdecl
#  define PYXIS_STDCALL __stdcall
#  define PYXIS_FASTCALL __fastcall
#  define PYXIS_THISCALL __thiscall
#  define PYXIS_VECTORCALL __vectorcall
#elif (defined(__i386__) || defined(_M_IX86)) && (defined(__GNUC__) || defined(__clang__))
#  define PYXIS_CDECL __attribute__((cdecl))
#  define PYXIS_STDCALL __attribute__((stdcall))
#  define PYXIS_FASTCALL __attribute__((fastcall))
#  define PYXIS_THISCALL __attribute__((thiscall))
#  define PYXIS_VECTORCALL __attribute__((sysv_abi))
#else
#  define PYXIS_CDECL
#  define PYXIS_STDCALL
#  define PYXIS_FASTCALL
#  define PYXIS_THISCALL
#  define PYXIS_VECTORCALL
#endif

namespace pyxis {
// Opaque size-correct placeholders for pyxis's atomic primitives. Projects
// that need real `<atomic>` semantics can shadow these with `using`-aliases
// in their own headers.
struct alignas(1) AtomicBool { ::std::uint8_t  _bytes[1]; };
struct alignas(1) AtomicU8   { ::std::uint8_t  _bytes[1]; };
struct alignas(2) AtomicU16  { ::std::uint8_t  _bytes[2]; };
struct alignas(4) AtomicU32  { ::std::uint8_t  _bytes[4]; };
struct alignas(8) AtomicU64  { ::std::uint8_t  _bytes[8]; };
struct alignas(1) AtomicI8   { ::std::uint8_t  _bytes[1]; };
struct alignas(2) AtomicI16  { ::std::uint8_t  _bytes[2]; };
struct alignas(4) AtomicI32  { ::std::uint8_t  _bytes[4]; };
struct alignas(8) AtomicI64  { ::std::uint8_t  _bytes[8]; };

// Wrapper that suppresses T's destructor (mirrors Rust's
// `core::mem::ManuallyDrop<T>`). Same layout as T; the inner value is
// exposed via `.value` and the wrapper itself does no work on destruction.
template <class T>
union ManuallyDrop {
    T value;
    ManuallyDrop() {}
    ~ManuallyDrop() {}
};
} // namespace pyxis
