// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace qualified_links_provider {
    /// An extern value.
    ::std::uint32_t*& get_shared_extern();

    /// A module with a freestanding function.
    using shared_function_t = void (*)();
    extern const shared_function_t shared_function;
} // namespace qualified_links_provider
