// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace qualified_links_consumer {
    struct Consumer;

    /// Test module-qualified doc-links to functions and extern values.
    ///
    /// See [`shared_function`](qualified_links_provider::shared_function) and
    /// [`shared_extern`](qualified_links_provider::shared_extern).
    struct alignas(1) Consumer {
        ::std::uint8_t _marker;
    };
    static_assert(sizeof(Consumer) == 0x1);
    static_assert(alignof(Consumer) == 1);
} // namespace qualified_links_consumer
