// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

#include "math.hpp"

namespace reexport_consumer {
    struct UsesReexport;

    struct alignas(4) UsesReexport {
        ::math::Vector3 position;
    };
    static_assert(sizeof(UsesReexport) == 0xC);
    static_assert(alignof(UsesReexport) == 4);
} // namespace reexport_consumer
