// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

#include "math.hpp"

namespace reexport {
    struct Bundle;

    /// A type that sits alongside the re-exports and uses them directly.
    struct alignas(4) Bundle {
        ::math::Matrix4 matrix;
        ::math::Vector3 position;
    };
    static_assert(sizeof(Bundle) == 0x4C);
    static_assert(alignof(Bundle) == 4);

    using Matrix4 = ::math::Matrix4;
    using Vector3 = ::math::Vector3;
} // namespace reexport
