// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace self_referential_generics {
    struct GameObject;
    struct TreeNode;
    template <class T> struct SharedPtr;
    template <class T> struct WeakPtr;

    /// A shared pointer to a type.
    template <class T>
    struct SharedPtr {
        T* px;
    };

    /// A weak pointer to a type.
    template <class T>
    struct WeakPtr {
        const T* px;
    };

    /// A game object that contains self-referential generic types.
    /// This tests that the compiler can handle cycles where:
    /// - GameObject contains SharedPtr<GameObject>
    /// - SharedPtr<T> contains *mut T
    /// - The pointer breaks the cycle, but only after generic substitution
    struct alignas(8) GameObject {
        ::std::uint32_t id;
        ::std::uint8_t _field_4[4];
        SharedPtr<GameObject> parent_object;
        WeakPtr<GameObject> weak_this;
        SharedPtr<GameObject> first_child;
        ::std::uint8_t _field_20[8];
    };
    static_assert(sizeof(GameObject) == 0x28);
    static_assert(alignof(GameObject) == 8);

    /// A tree node with self-referential pointers.
    struct alignas(8) TreeNode {
        ::std::uint32_t value;
        ::std::uint8_t _field_4[4];
        SharedPtr<TreeNode> left;
        SharedPtr<TreeNode> right;
    };
    static_assert(sizeof(TreeNode) == 0x18);
    static_assert(alignof(TreeNode) == 8);
} // namespace self_referential_generics
