// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace singleton {
    struct TestType;

    struct alignas(4) TestType {
        ::std::uint32_t field_1;

        static TestType* singleton();
    };
    static_assert(sizeof(TestType) == 0x4);
    static_assert(alignof(TestType) == 4);
} // namespace singleton
