// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace two_base_classes {
    struct BaseA;
    struct BaseAVftable;
    struct BaseB;
    struct BaseBVftable;
    struct Derived;
    struct DerivedVftable;

    struct alignas(8) BaseA {
        const BaseAVftable* vftable;
        ::std::uint64_t field_a;

        const BaseAVftable* _vftable_ptr() const;
        ::std::int32_t base_a_vfunc(::std::int32_t a) const;
        ::std::int32_t base_a_associated(::std::int32_t a) const;
    };
    static_assert(sizeof(BaseA) == 0x10);
    static_assert(alignof(BaseA) == 8);

    struct alignas(8) BaseAVftable {
        ::std::int32_t (*base_a_vfunc)(const void*, ::std::int32_t);
    };
    static_assert(sizeof(BaseAVftable) == 0x8);
    static_assert(alignof(BaseAVftable) == 8);

    struct alignas(8) BaseB {
        const BaseBVftable* vftable;
        ::std::uint64_t field_b;

        const BaseBVftable* _vftable_ptr() const;
        ::std::int32_t base_b_vfunc(::std::int32_t a) const;
        ::std::int32_t base_b_associated(::std::int32_t a) const;
    };
    static_assert(sizeof(BaseB) == 0x10);
    static_assert(alignof(BaseB) == 8);

    struct alignas(8) BaseBVftable {
        ::std::int32_t (*base_b_vfunc)(const void*, ::std::int32_t);
    };
    static_assert(sizeof(BaseBVftable) == 0x8);
    static_assert(alignof(BaseBVftable) == 8);

    struct alignas(8) Derived {
        BaseA base_a;
        BaseB base_b;

        operator BaseA&() { return this->base_a; }
        operator const BaseA&() const { return this->base_a; }

        operator BaseB&() { return this->base_b; }
        operator const BaseB&() const { return this->base_b; }

        const DerivedVftable* _vftable_ptr() const;
        ::std::int32_t base_a_vfunc(::std::int32_t a) const;
        ::std::int32_t derived_vfunc(::std::int32_t a) const;
        ::std::int32_t base_a_associated(::std::int32_t a) const;
        ::std::int32_t base_b_associated(::std::int32_t a) const;
        ::std::int32_t base_b_vfunc(::std::int32_t a) const;
        ::std::int32_t derived_associated(::std::int32_t a) const;
    };
    static_assert(sizeof(Derived) == 0x20);
    static_assert(alignof(Derived) == 8);

    struct alignas(8) DerivedVftable {
        ::std::int32_t (*base_a_vfunc)(const void*, ::std::int32_t);
        ::std::int32_t (*derived_vfunc)(const void*, ::std::int32_t);
    };
    static_assert(sizeof(DerivedVftable) == 0x10);
    static_assert(alignof(DerivedVftable) == 8);

    inline const BaseAVftable* BaseA::_vftable_ptr() const { return this->vftable; }
    inline ::std::int32_t BaseA::base_a_vfunc(::std::int32_t a) const {
        return _vftable_ptr()->base_a_vfunc(this, a);
    }
    inline ::std::int32_t BaseA::base_a_associated(::std::int32_t a) const {
        using fn_t = ::std::int32_t (*)(const void*, ::std::int32_t);
        return reinterpret_cast<fn_t>(0x123)(this, a);
    }
    inline const BaseBVftable* BaseB::_vftable_ptr() const { return this->vftable; }
    inline ::std::int32_t BaseB::base_b_vfunc(::std::int32_t a) const {
        return _vftable_ptr()->base_b_vfunc(this, a);
    }
    inline ::std::int32_t BaseB::base_b_associated(::std::int32_t a) const {
        using fn_t = ::std::int32_t (*)(const void*, ::std::int32_t);
        return reinterpret_cast<fn_t>(0x456)(this, a);
    }
    inline const DerivedVftable* Derived::_vftable_ptr() const { return reinterpret_cast<const DerivedVftable*>(this->base_a._vftable_ptr()); }
    inline ::std::int32_t Derived::base_a_vfunc(::std::int32_t a) const {
        return _vftable_ptr()->base_a_vfunc(this, a);
    }
    inline ::std::int32_t Derived::derived_vfunc(::std::int32_t a) const {
        return _vftable_ptr()->derived_vfunc(this, a);
    }
    inline ::std::int32_t Derived::base_a_associated(::std::int32_t a) const {
        return this->base_a.base_a_associated(a);
    }
    inline ::std::int32_t Derived::base_b_associated(::std::int32_t a) const {
        return this->base_b.base_b_associated(a);
    }
    inline ::std::int32_t Derived::base_b_vfunc(::std::int32_t a) const {
        return this->base_b.base_b_vfunc(a);
    }
    inline ::std::int32_t Derived::derived_associated(::std::int32_t a) const {
        using fn_t = ::std::int32_t (*)(const void*, ::std::int32_t);
        return reinterpret_cast<fn_t>(0x789)(this, a);
    }
} // namespace two_base_classes
