// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace math {
    struct Vector3;
} // namespace math

namespace type_alias_reexport {
    struct Wrapper;

    /// Uses an alias from another module as a re-export.
    /// This works because visibility is checked at alias definition time.
    struct alignas(8) Wrapper {
        const ::math::Vector3* data;
    };
    static_assert(sizeof(Wrapper) == 0x8);
    static_assert(alignof(Wrapper) == 8);
} // namespace type_alias_reexport
