// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

#include "generics.hpp"

namespace math {
    struct Vector3;
} // namespace math

namespace type_aliases {
    struct ConcreteAliasContainer;
    struct Container;
    struct GenericAliasContainer;

    /// Generic const pointer type alias
    template <class T>
    using ConstPtr = const T*;

    /// Alias for MapEntry with type parameters
    template <class K, class V>
    using Entry = ::generics::MapEntry<K, V>;

    /// Generic pointer type alias
    template <class T>
    using Ptr = T*;

    /// Pointer to a generic type
    template <class T>
    using SharedPtr = ::generics::Shared<T>*;

    /// Alias that wraps a generic type with a type parameter
    template <class T>
    using SharedRef = ::generics::Shared<T>;

    /// Alias for weak pointer to a type
    template <class T>
    using WeakRef = ::generics::WeakPtr<T>;

    /// Container using concrete aliases
    struct alignas(8) ConcreteAliasContainer {
        ::generics::Shared<::math::Vector3>* vec_shared;
        ::generics::MapEntry<::std::uint32_t, ::math::Vector3> vec_entry;
    };
    static_assert(sizeof(ConcreteAliasContainer) == 0x18);
    static_assert(alignof(ConcreteAliasContainer) == 8);

    /// Container using the non-generic type aliases
    struct alignas(8) Container {
        const ::math::Vector3* ptr;
        ::std::int32_t* int_ptr;
    };
    static_assert(sizeof(Container) == 0x10);
    static_assert(alignof(Container) == 8);

    /// Container using generic aliases with concrete types
    struct alignas(8) GenericAliasContainer {
        ::generics::Shared<::math::Vector3> shared_vec;
        ::generics::WeakPtr<::math::Vector3> weak_vec;
        ::generics::MapEntry<::std::uint32_t, ::math::Vector3> entry;
        ::math::Vector3* vec_ptr;
        const ::math::Vector3* const_vec_ptr;
    };
    static_assert(sizeof(GenericAliasContainer) == 0x30);
    static_assert(alignof(GenericAliasContainer) == 8);

    /// Alias for a mutable i32 pointer.
    using IntMutPtr = ::std::int32_t*;

    /// Alias for a Vector3 pointer.
    /// Demonstrates doc comments on type aliases.
    using Vec3Ptr = const ::math::Vector3*;

    /// Concrete alias to Entry<u32, Vector3>
    using VecEntry = ::generics::MapEntry<::std::uint32_t, ::math::Vector3>;

    /// Concrete alias to SharedPtr<Vector3>
    using VecSharedPtr = ::generics::Shared<::math::Vector3>*;
} // namespace type_aliases
