// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace unicode {
    struct Unicode;
    struct UnicodeVftable;

    /// A type — with an emdash — and café.
    struct alignas(8) Unicode {
        const UnicodeVftable* vftable;
        /// field — naïve
        ::std::uint64_t field_1;

        const UnicodeVftable* _vftable_ptr() const;
        /// vfunc — 一期一会
        void test_vfunc() const;
        /// impl func — ☃ snowman
        ///
        /// second line — 愛
        void test_func() const;
    };
    static_assert(sizeof(Unicode) == 0x10);
    static_assert(alignof(Unicode) == 8);

    struct alignas(8) UnicodeVftable {
        /// vfunc — 一期一会
        void (*test_vfunc)(const void*);
    };
    static_assert(sizeof(UnicodeVftable) == 0x8);
    static_assert(alignof(UnicodeVftable) == 8);
} // namespace unicode
