// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace unions {
    struct InlineScratch;
    struct TaggedValue;
    struct Vec2;
    union Anchored;
    union Geometry;
    union InlineScratchDataUnion;
    union Outer;
    union OuterInnerUnion;
    union OversizedSlot;
    union PackedPair;
    union PaddedSlot;
    union Payload;
    union ZeroInit;

    /// A pinned union can be neither copied nor moved.
    union alignas(8) Anchored {
        ::std::uint64_t value;
        ::std::uint32_t halves[2];

        Anchored(const Anchored&) = delete;
        Anchored(Anchored&&) = delete;
        Anchored& operator=(const Anchored&) = delete;
        Anchored& operator=(Anchored&&) = delete;
    };
    static_assert(sizeof(Anchored) == 0x8);
    static_assert(alignof(Anchored) == 8);

    /// Members can be structs, and the union takes the strictest alignment and the
    /// largest size among them.
    struct alignas(8) Vec2 {
        float x;
        float y;
    };
    static_assert(sizeof(Vec2) == 0x8);
    static_assert(alignof(Vec2) == 8);

    union alignas(8) Geometry {
        Vec2 point;
        double scalar;
        ::std::uint8_t raw[8];
    };
    static_assert(sizeof(Geometry) == 0x8);
    static_assert(alignof(Geometry) == 8);

    union alignas(8) InlineScratchDataUnion {
        ::std::uint64_t as_u64;
        ::std::uint8_t as_bytes[8];
    };
    static_assert(sizeof(InlineScratchDataUnion) == 0x8);
    static_assert(alignof(InlineScratchDataUnion) == 8);

    /// A union declared inline in field position. It lowers to a generated sibling
    /// item named `InlineScratchDataUnion`.
    struct alignas(8) InlineScratch {
        ::std::uint16_t tag;
        ::std::uint8_t _reserved[6];
        InlineScratchDataUnion data;
    };
    static_assert(sizeof(InlineScratch) == 0x10);
    static_assert(alignof(InlineScratch) == 8);

    union alignas(2) OuterInnerUnion {
        ::std::uint16_t lo;
        ::std::uint8_t hi[2];
    };
    static_assert(sizeof(OuterInnerUnion) == 0x2);
    static_assert(alignof(OuterInnerUnion) == 2);

    /// A union nested inside another union, plus a nested item declaration in a
    /// union body.
    union alignas(4) Outer {
        ::std::uint32_t raw;
        OuterInnerUnion inner;

        /// A type declared inside a union body. Nested declarations work here
        /// exactly as they do in a `type` body.
        struct Header {
            ::std::uint32_t magic;
        };
    };
    static_assert(sizeof(Outer) == 0x4);
    static_assert(alignof(Outer) == 4);

    /// `#[size]` alone asks for more room than any member needs, so the union gains
    /// a whole-width `_padding` member. Rounding up to `#[align]` needs no such help
    /// — see [`PaddedSlot`](@ref unions::PaddedSlot), which gets none.
    union alignas(8) OversizedSlot {
        ::std::uint32_t small;
        ::std::uint64_t medium;
        ::std::uint8_t _padding[16];
    };
    static_assert(sizeof(OversizedSlot) == 0x10);
    static_assert(alignof(OversizedSlot) == 8);

    /// `#[packed]` drops the union's alignment to 1.
    #pragma pack(push, 1)
    union alignas(1) PackedPair {
        ::std::uint16_t word;
        ::std::uint8_t bytes[2];
    };
    #pragma pack(pop)
    static_assert(sizeof(PackedPair) == 0x2);
    static_assert(alignof(PackedPair) == 1);

    /// `#[size]` pads a union out beyond its largest member, and `#[align]`
    /// over-aligns it.
    union alignas(16) PaddedSlot {
        ::std::uint32_t small;
        ::std::uint64_t medium;
    };
    static_assert(sizeof(PaddedSlot) == 0x10);
    static_assert(alignof(PaddedSlot) == 16);

    /// A value whose bytes have several competing readings. Which one applies is
    /// decided by [`TaggedValue::kind`](@ref unions::TaggedValue::kind), not by the union itself.
    union alignas(8) Payload {
        /// Read as a signed integer.
        ::std::int32_t as_int;
        /// Read as a float.
        float as_float;
        /// Read as a pointer to something else.
        ::std::int32_t* as_ptr;
    };
    static_assert(sizeof(Payload) == 0x8);
    static_assert(alignof(Payload) == 8);

    /// A tagged value pairing a discriminant with a [`Payload`](@ref unions::Payload). When `kind` is 0,
    /// the live member is [`Payload::as_int`](@ref unions::Payload::as_int).
    struct alignas(8) TaggedValue {
        ::std::uint32_t kind;
        ::std::uint8_t _field_4[4];
        Payload payload;
    };
    static_assert(sizeof(TaggedValue) == 0x10);
    static_assert(alignof(TaggedValue) == 8);

    /// A defaultable union gets a hand-written `Default` in Rust — a union can't
    /// derive one, because nothing knows which member is live.
    union alignas(4) ZeroInit {
        ::std::uint32_t count;
        ::std::uint8_t flags[4];
    };
    static_assert(sizeof(ZeroInit) == 0x4);
    static_assert(alignof(ZeroInit) == 4);
} // namespace unions
