// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace vftable_indices {
    struct IndexedVftable;
    struct IndexedVftableVftable;

    struct alignas(8) IndexedVftable {
        const IndexedVftableVftable* vftable;
        ::std::uint64_t field;

        const IndexedVftableVftable* _vftable_ptr() const;
        ::std::uint32_t first() const;
        ::std::int32_t second(::std::int32_t x) const;
        ::std::uint32_t third() const;
    };
    static_assert(sizeof(IndexedVftable) == 0x10);
    static_assert(alignof(IndexedVftable) == 8);

    struct alignas(8) IndexedVftableVftable {
        ::std::uint32_t (*first)(const void*);
        void (*_vfunc_1)(void*);
        ::std::int32_t (*second)(const void*, ::std::int32_t);
        ::std::uint32_t (*third)(const void*);
    };
    static_assert(sizeof(IndexedVftableVftable) == 0x20);
    static_assert(alignof(IndexedVftableVftable) == 8);
} // namespace vftable_indices
