// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace world {
    struct World;

    /// A handle to the world, defined directly in the folder module.
    struct alignas(8) World {
        ::std::uint64_t id;
    };
    static_assert(sizeof(World) == 0x8);
    static_assert(alignof(World) == 8);
} // namespace world
