// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace world {
    struct World;
} // namespace world
namespace world::weather {
    struct Weather;
} // namespace world::weather

namespace world_consumer {
    struct WorldConsumer;

    /// Consumes the world. Doc-links a type from a deeper, un-imported module
    /// ([`DeepMarker`](world::deep::marker::DeepMarker)) to exercise the
    /// doc-import path: the emitted `use` must split module and item segments at
    /// the declaring module's prefix, not this module's depth.
    struct alignas(8) WorldConsumer {
        ::world::weather::Weather* weather;
        ::world::World* world;
    };
    static_assert(sizeof(WorldConsumer) == 0x10);
    static_assert(alignof(WorldConsumer) == 8);
} // namespace world_consumer
