// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace zero_size_type {
    struct Holder;
    struct Marker;

    /// A fieldless type given a nonzero footprint via `#[min_size]`.
    /// Without this attribute, embedding it would be rejected.
    struct alignas(1) Marker {
        ::std::uint8_t _field_0[8];
    };
    static_assert(sizeof(Marker) == 0x8);
    static_assert(alignof(Marker) == 1);

    /// A type that embeds Marker. Both backends must agree on layout:
    /// marker occupies 8 bytes (min_size, alignment 1).
    struct alignas(8) Holder {
        Marker marker;
        ::std::uint32_t value;
        ::std::uint8_t _field_c[4];
    };
    static_assert(sizeof(Holder) == 0x10);
    static_assert(alignof(Holder) == 8);
} // namespace zero_size_type
