// This file has been generated by Specta. DO NOT EDIT.

export type JsonArgument = { type: "const_self" } | { type: "mut_self" } | { type: "field"; name: string; type_ref: JsonType };

/**
 * Backend configuration with prologue and epilogue
 */
export type JsonBackend = { 
/**
 * Prologue code inserted at the beginning of generated output
 */
prologue: string | null; 
/**
 * Epilogue code inserted at the end of generated output
 */
epilogue: string | null };

export type JsonBitflag = { 
/**
 * Flag name
 */
name: string; 
/**
 * Flag value
 */
value: number };

export type JsonBitflagsDefinition = { 
/**
 * Documentation
 */
doc: string | null; 
/**
 * Underlying type
 */
underlying_type: JsonType; 
/**
 * Bitflag fields
 */
flags: JsonBitflag[]; 
/**
 * Singleton address
 */
singleton: number | null; 
/**
 * Whether the bitflags is copyable
 */
copyable: boolean; 
/**
 * Whether the bitflags is cloneable
 */
cloneable: boolean; 
/**
 * Default flag index
 */
default: number | null };

export type JsonCallingConvention = "c" | "cdecl" | "stdcall" | "fastcall" | "thiscall" | "vectorcall" | "system";

/**
 * Top-level JSON documentation structure
 */
export type JsonDocumentation = { 
/**
 * Pointer size for the target platform
 */
pointer_size: number; 
/**
 * Project name
 */
project_name: string; 
/**
 * Map of absolute paths to items
 */
items: { [key in string]: JsonItem }; 
/**
 * Nested module hierarchy
 */
modules: { [key in string]: JsonModule }; 
/**
 * Source file paths indexed by file ID (index 0 and 1 are reserved for internal/test)
 */
source_paths: string[] };

export type JsonEnumDefinition = { 
/**
 * Documentation
 */
doc: string | null; 
/**
 * Underlying type
 */
underlying_type: JsonType; 
/**
 * Enum variants
 */
variants: JsonEnumVariant[]; 
/**
 * Associated functions
 */
associated_functions: JsonFunction[]; 
/**
 * Singleton address
 */
singleton: number | null; 
/**
 * Whether the enum is copyable
 */
copyable: boolean; 
/**
 * Whether the enum is cloneable
 */
cloneable: boolean; 
/**
 * Default variant index
 */
default: number | null };

export type JsonEnumVariant = { 
/**
 * Variant name
 */
name: string; 
/**
 * Variant value
 */
value: number };

export type JsonExternValue = { 
/**
 * Visibility
 */
visibility: JsonVisibility; 
/**
 * Variable name
 */
name: string; 
/**
 * Type
 */
type_ref: JsonType; 
/**
 * Memory address
 */
address: number };

export type JsonFunction = { 
/**
 * Visibility
 */
visibility: JsonVisibility; 
/**
 * Function name
 */
name: string; 
/**
 * Documentation
 */
doc: string | null; 
/**
 * Function body (how it's implemented)
 */
body: JsonFunctionBody; 
/**
 * Arguments
 */
arguments: JsonArgument[]; 
/**
 * Return type
 */
return_type: JsonType | null; 
/**
 * Calling convention
 */
calling_convention: JsonCallingConvention };

export type JsonFunctionArgument = { name: string; type_ref: JsonType };

export type JsonFunctionBody = { type: "address"; address: number } | { type: "field"; field: string; function_name: string } | { type: "vftable"; function_name: string };

/**
 * An item (type, enum, or bitflags) in the documentation
 */
export type JsonItem = { 
/**
 * Item path
 */
path: string; 
/**
 * Visibility
 */
visibility: JsonVisibility; 
/**
 * Size in bytes
 */
size: number; 
/**
 * Alignment in bytes
 */
alignment: number; 
/**
 * Item category (Defined, Predefined, Extern)
 */
category: JsonItemCategory; 
/**
 * Item kind and details
 */
kind: JsonItemKind; 
/**
 * Source location (file and line) - None for predefined/internal items
 */
source: JsonSourceLocation | null };

export type JsonItemCategory = "defined" | "predefined" | "extern";

export type JsonItemKind = ({ type: "type" } & JsonTypeDefinition) | ({ type: "enum" } & JsonEnumDefinition) | ({ type: "bitflags" } & JsonBitflagsDefinition) | ({ type: "type_alias" } & JsonTypeAliasDefinition);

/**
 * A module containing items and potentially submodules
 */
export type JsonModule = { 
/**
 * Module documentation
 */
doc: string | null; 
/**
 * Items defined directly in this module
 */
items: string[]; 
/**
 * Child modules
 */
submodules: { [key in string]: JsonModule }; 
/**
 * Extern values (global variables)
 */
extern_values: JsonExternValue[]; 
/**
 * Freestanding functions
 */
functions: JsonFunction[]; 
/**
 * Backend configurations (prologue/epilogue for code generation)
 */
backends: { [key in string]: JsonBackend[] } };

export type JsonRegion = { 
/**
 * Visibility
 */
visibility: JsonVisibility; 
/**
 * Field name
 */
name: string | null; 
/**
 * Documentation
 */
doc: string | null; 
/**
 * Type reference
 */
type_ref: JsonType; 
/**
 * Offset in bytes from start of structure
 */
offset: number; 
/**
 * Size in bytes
 */
size: number; 
/**
 * Alignment in bytes
 */
alignment: number; 
/**
 * Whether this is a base class field
 */
is_base: boolean };

/**
 * Source location of an item (file index and line number)
 */
export type JsonSourceLocation = { 
/**
 * Index into the source_paths array in JsonDocumentation
 */
file_index: number; 
/**
 * Line number (1-indexed)
 */
line: number };

export type JsonType = { type: "raw"; path: string } | { type: "const_pointer"; inner: JsonType } | { type: "mut_pointer"; inner: JsonType } | { type: "array"; inner: JsonType; size: number } | { type: "function"; calling_convention: JsonCallingConvention; arguments: JsonFunctionArgument[]; return_type: JsonType | null };

export type JsonTypeAliasDefinition = { 
/**
 * Documentation
 */
doc: string | null; 
/**
 * The resolved target type that this alias refers to
 */
target: JsonType };

export type JsonTypeDefinition = { 
/**
 * Documentation
 */
doc: string | null; 
/**
 * Fields/regions
 */
fields: JsonRegion[]; 
/**
 * Associated functions
 */
associated_functions: JsonFunction[]; 
/**
 * Virtual function table
 */
vftable: JsonTypeVftable | null; 
/**
 * Singleton address
 */
singleton: number | null; 
/**
 * Whether the type is copyable
 */
copyable: boolean; 
/**
 * Whether the type is cloneable
 */
cloneable: boolean; 
/**
 * Whether the type is defaultable
 */
defaultable: boolean; 
/**
 * Whether the type is packed
 */
packed: boolean };

export type JsonTypeVftable = { 
/**
 * Virtual functions
 */
functions: JsonFunction[] };

export type JsonVisibility = "public" | "private";