// This file has been generated by Specta. DO NOT EDIT.

export type JsonArgument = { type: "const_self" } | { type: "mut_self" } | { type: "field"; name: string; type_ref: JsonType };

export type JsonBitflag = { 
/**
 * Flag name
 */
name: string; 
/**
 * Flag value
 */
value: number; 
/**
 * Documentation
 */
doc?: string | null; doc_links?: JsonDocLink[]; 
/**
 * Source location (file and line)
 */
source: JsonSourceLocation | null };

export type JsonBitflagsDefinition = { 
/**
 * Documentation
 */
doc: string | null; doc_links?: JsonDocLink[]; 
/**
 * Underlying type
 */
underlying_type: JsonType; 
/**
 * Bitflag fields
 */
flags: JsonBitflag[]; 
/**
 * Singleton address
 */
singleton: number | null; 
/**
 * Whether the bitflags is copyable
 */
copyable: boolean; 
/**
 * Whether the bitflags is cloneable
 */
cloneable: boolean; 
/**
 * Default flag index
 */
default: number | null; 
/**
 * Whether the bitflags is pinned (non-relocatable)
 */
pinned: boolean; 
/**
 * Item paths of nested items declared inside this bitflags body
 */
nested_items?: string[] };

export type JsonCallingConvention = "c" | "cdecl" | "stdcall" | "fastcall" | "thiscall" | "vectorcall" | "system";

/**
 * `#[cfg(...)]` predicate AST, mirroring the parser's
 * [`crate::parser::cfg::CfgPredicate`] shape with locations stripped.
 * Emitted on items/functions so documentation consumers can decide
 * per-backend rendering without re-parsing.
 */
export type JsonCfg = 
/**
 * A bare ident atom: `#[cfg(test)]`.
 */
{ type: "ident"; name: string } | 
/**
 * A key/value atom: `#[cfg(backend = "cpp")]`.
 */
{ type: "key_value"; key: string; value: string } | 
/**
 * `any(...)` combinator.
 */
{ type: "any"; predicates: JsonCfg[] } | 
/**
 * `all(...)` combinator.
 */
{ type: "all"; predicates: JsonCfg[] } | 
/**
 * `not(...)` combinator.
 */
{ type: "not"; predicate: JsonCfg };

export type JsonConstValue = { kind: "int"; value: number } | { kind: "float"; value: number } | { kind: "string"; value: string } | { kind: "enum_value"; path: string };

export type JsonConstantDefinition = { 
/**
 * Documentation
 */
doc: string | null; doc_links?: JsonDocLink[]; 
/**
 * The type annotation of the constant
 */
value_type: JsonType; 
/**
 * The compile-time value
 */
value: JsonConstValue };

/**
 * A resolved rustdoc-style intra-doc link found in a doc comment. Consumers
 * rewrite the matching `[`text`]` / `[label](text)` in the markdown into a
 * link to `(target_kind, path, anchor)`.
 */
export type JsonDocLink = { 
/**
 * The link path as written in the doc (e.g. `Type::method`, `Action`).
 */
text: string; 
/**
 * Whether `path` names an item or a module.
 */
target_kind: JsonDocLinkTargetKind; 
/**
 * Absolute path to the item or module the link resolves to.
 */
path: string; 
/**
 * Anchor within the target page (e.g. `field-m_Foo`, `variant-Bar`), if the
 * link points at a member rather than the page itself.
 */
anchor?: string | null };

export type JsonDocLinkTargetKind = "item" | "module";

/**
 * Top-level JSON documentation structure
 */
export type JsonDocumentation = { 
/**
 * Schema version. See [`CURRENT_SCHEMA_VERSION`]. Older documents
 * (pre-v2) omit this field; consumers should treat a missing value
 * as v1.
 */
schema_version?: number; 
/**
 * Version of pyxis that generated this document (from
 * `CARGO_PKG_VERSION`), so downstream consumers can tell which
 * toolchain produced a given doc set. Surfaced by the pyxis-defs
 * `build.py` index, for example.
 */
pyxis_version?: string; 
/**
 * Pointer size for the target platform
 */
pointer_size: number; 
/**
 * Project name
 */
project_name: string; 
/**
 * Map of absolute paths to items
 */
items: { [key in string]: JsonItem }; 
/**
 * Nested module hierarchy
 */
modules: { [key in string]: JsonModule }; 
/**
 * Source file paths indexed by file ID (index 0 and 1 are reserved for internal/test)
 */
source_paths: string[] };

export type JsonEnumDefinition = { 
/**
 * Documentation
 */
doc: string | null; doc_links?: JsonDocLink[]; 
/**
 * Underlying type
 */
underlying_type: JsonType; 
/**
 * Enum variants
 */
variants: JsonEnumVariant[]; 
/**
 * Associated functions
 */
associated_functions: JsonFunction[]; 
/**
 * Singleton address
 */
singleton: number | null; 
/**
 * Whether the enum is copyable
 */
copyable: boolean; 
/**
 * Whether the enum is cloneable
 */
cloneable: boolean; 
/**
 * Default variant index
 */
default: number | null; 
/**
 * Whether the enum is pinned (non-relocatable)
 */
pinned: boolean; 
/**
 * Item paths of nested items declared inside this enum body
 */
nested_items?: string[] };

export type JsonEnumVariant = { 
/**
 * Variant name
 */
name: string; 
/**
 * Variant value
 */
value: number; 
/**
 * Documentation
 */
doc?: string | null; doc_links?: JsonDocLink[]; 
/**
 * Source location (file and line)
 */
source: JsonSourceLocation | null };

/**
 * An `extern` value item (a global at a fixed address). Emitted as an item
 * page like any other definition; `visibility`, `path`, and `source` live on
 * the enclosing [`JsonItem`].
 */
export type JsonExternValueDefinition = { 
/**
 * Documentation
 */
doc: string | null; doc_links?: JsonDocLink[]; 
/**
 * The type annotation of the extern value
 */
value_type: JsonType; 
/**
 * Memory address
 */
address: number };

export type JsonFunction = { 
/**
 * Visibility
 */
visibility: JsonVisibility; 
/**
 * Function name
 */
name: string; 
/**
 * Documentation
 */
doc: string | null; doc_links?: JsonDocLink[]; 
/**
 * Function body (how it's implemented)
 */
body: JsonFunctionBody; 
/**
 * Arguments
 */
arguments: JsonArgument[]; 
/**
 * Return type
 */
return_type: JsonType | null; 
/**
 * Calling convention
 */
calling_convention: JsonCallingConvention; 
/**
 * Method-level type parameters declared at the impl block beyond the
 * parent struct's own type parameters (`Y` in `impl<T, Y> Foo<T> {...}`).
 */
method_type_parameters?: string[]; 
/**
 * `#[cfg(...)]` predicate the function is gated by, if any. Methods
 * inherit the conjunction of their impl block's cfg and their own.
 */
cfg?: JsonCfg | null; 
/**
 * Source location (file and line)
 */
source: JsonSourceLocation | null };

export type JsonFunctionArgument = { name: string; type_ref: JsonType };

export type JsonFunctionBody = { type: "address"; address: number } | { type: "field"; field: string; function_name: string } | { type: "vftable"; function_name: string } | 
/**
 * Body supplied by the target backend's prologue/epilogue (the pyxis
 * `#[external_body]` attribute).
 */
{ type: "external" };

/**
 * An item (type, enum, or bitflags) in the documentation
 */
export type JsonItem = { 
/**
 * Item path
 */
path: string; 
/**
 * Visibility
 */
visibility: JsonVisibility; 
/**
 * Type parameters for generic types (e.g., ["T", "U"] for `type Map<T, U>`)
 */
type_parameters?: string[]; 
/**
 * Size in bytes
 */
size: number; 
/**
 * Alignment in bytes
 */
alignment: number; 
/**
 * Item category (Defined, Predefined, Extern)
 */
category: JsonItemCategory; 
/**
 * For `extern type`s: the backend type bindings (`#[cpp_name]`,
 * `#[cpp_header]`, `#[rust_name]`) that say which concrete C++/Rust type
 * the opaque extern maps to. Empty/None for non-extern items.
 */
cpp_name?: string | null; cpp_header?: string | null; rust_name?: string | null; 
/**
 * Item kind and details
 */
kind: JsonItemKind; 
/**
 * `#[cfg(...)]` predicate the item is gated by, if any. Always
 * emitted (the JSON output is documentation, not a build target);
 * downstream tooling decides how to render and/or filter.
 */
cfg?: JsonCfg | null; 
/**
 * Source location (file and line) - None for predefined/internal items
 */
source: JsonSourceLocation | null };

export type JsonItemCategory = "defined" | "predefined" | "extern";

export type JsonItemKind = ({ type: "type" } & JsonTypeDefinition) | ({ type: "enum" } & JsonEnumDefinition) | ({ type: "bitflags" } & JsonBitflagsDefinition) | ({ type: "type_alias" } & JsonTypeAliasDefinition) | ({ type: "constant" } & JsonConstantDefinition) | ({ type: "extern_value" } & JsonExternValueDefinition);

/**
 * A module containing items and potentially submodules
 */
export type JsonModule = { 
/**
 * Module documentation
 */
doc: string | null; doc_links?: JsonDocLink[]; 
/**
 * Items defined directly in this module
 */
items: string[]; 
/**
 * Explicit re-exports (`pub use`): items imported and re-exported from this
 * module. Each points at the canonical path of the item being re-exported.
 */
reexports?: JsonReexport[]; 
/**
 * Child modules
 */
submodules: { [key in string]: JsonModule }; 
/**
 * Freestanding functions
 */
functions: JsonFunction[]; 
/**
 * Standalone `prologue`/`epilogue` splices, in source order, each with
 * its own optional `cfg` gate.
 */
splices: JsonSplice[]; 
/**
 * Source location (file and line) - None for synthesized/folder modules
 */
source?: JsonSourceLocation | null };

/**
 * An explicit re-export (`pub use path::Item;`). `name` is the local name the
 * item is re-exported as; `path` is the canonical absolute path of the target
 * item (following any re-export chain), which the viewer links to.
 */
export type JsonReexport = { 
/**
 * The local name the item is re-exported as.
 */
name: string; 
/**
 * Canonical absolute path of the re-exported item.
 */
path: string };

export type JsonRegion = { 
/**
 * Visibility
 */
visibility: JsonVisibility; 
/**
 * Field name
 */
name: string | null; 
/**
 * Documentation
 */
doc: string | null; doc_links?: JsonDocLink[]; 
/**
 * Type reference
 */
type_ref: JsonType; 
/**
 * Offset in bytes from start of structure
 */
offset: number; 
/**
 * Size in bytes
 */
size: number; 
/**
 * Alignment in bytes
 */
alignment: number; 
/**
 * Whether this is a base class field
 */
is_base: boolean; 
/**
 * Source location (file and line) - None for generated/padding fields
 */
source: JsonSourceLocation | null };

/**
 * Source location of an item (file index and line number)
 */
export type JsonSourceLocation = { 
/**
 * Index into the source_paths array in JsonDocumentation
 */
file_index: number; 
/**
 * Line number (1-indexed)
 */
line: number };

/**
 * A standalone `prologue`/`epilogue` splice: raw backend code spliced into
 * the module's generated output.
 * 
 * `cfg`, when present, gates which backends emit it (`null`/absent = every
 * backend). `definition` routes the splice into the C++ `.cpp` source
 * rather than the header (only meaningful for cpp-gated splices).
 * `for_type`, when set, is the resolved absolute item path this splice is
 * attributed to (`prologue/epilogue for <Type>`); the viewer renders such
 * splices on the owning type's page rather than the module page.
 */
export type JsonSplice = { 
/**
 * Whether the splice is a prologue or an epilogue.
 */
kind: JsonSpliceKind; 
/**
 * `#[cfg(...)]` gate; `null`/absent means emitted for every backend.
 */
cfg?: JsonCfg | null; 
/**
 * Whether this is a `definition` splice (C++ `.cpp` source).
 */
definition: boolean; 
/**
 * Resolved absolute item path this splice is attributed to, when tagged
 * with `for <Type>`. `None`/absent means module-level rendering.
 */
for_type?: string | null; 
/**
 * The spliced code text.
 */
text: string };

/**
 * Which end of the module's generated output a splice attaches to.
 */
export type JsonSpliceKind = "prologue" | "epilogue";

export type JsonType = { type: "raw"; path: string } | 
/**
 * A generic type instantiation, e.g., `SharedPtr<GameObject>`
 */
{ type: "generic"; base: string; args: JsonType[] } | 
/**
 * A type parameter reference, e.g., `T` inside a generic type definition
 */
{ type: "type_parameter"; name: string } | { type: "const_pointer"; inner: JsonType } | { type: "mut_pointer"; inner: JsonType } | { type: "array"; inner: JsonType; size: number } | { type: "function"; calling_convention: JsonCallingConvention; arguments: JsonFunctionArgument[]; return_type: JsonType | null };

export type JsonTypeAliasDefinition = { 
/**
 * Documentation
 */
doc: string | null; doc_links?: JsonDocLink[]; 
/**
 * The resolved target type that this alias refers to
 */
target: JsonType };

export type JsonTypeDefinition = { 
/**
 * Documentation
 */
doc: string | null; doc_links?: JsonDocLink[]; 
/**
 * Fields/regions
 */
fields: JsonRegion[]; 
/**
 * Associated functions
 */
associated_functions: JsonFunction[]; 
/**
 * Virtual function table
 */
vftable: JsonTypeVftable | null; 
/**
 * Singleton address
 */
singleton: number | null; 
/**
 * Whether the type is copyable
 */
copyable: boolean; 
/**
 * Whether the type is cloneable
 */
cloneable: boolean; 
/**
 * Whether the type is defaultable
 */
defaultable: boolean; 
/**
 * Whether the type is packed
 */
packed: boolean; 
/**
 * Whether the type is pinned (non-relocatable)
 */
pinned: boolean; 
/**
 * Item paths of nested items declared inside this type body
 */
nested_items?: string[] };

export type JsonTypeVftable = { 
/**
 * Virtual functions
 */
functions: JsonFunction[] };

export type JsonVisibility = "public" | "private";