// @generated by pyxis — do not edit

#include "calling_conventions.hpp"

namespace calling_conventions {
    using c_freestanding_t = ::std::int32_t (PYXIS_CDECL *)(::std::int32_t, ::std::int32_t);
    const c_freestanding_t c_freestanding = reinterpret_cast<c_freestanding_t>(0x1000);

    ::std::int32_t Cc::c_method(::std::int32_t x) {
        using fn_t = ::std::int32_t (PYXIS_CDECL *)(void*, ::std::int32_t);
        return reinterpret_cast<fn_t>(0x1001)(this, x);
    }
} // namespace calling_conventions
