// @generated by pyxis — do not edit

#include "definition_body.hpp"

#include <cstdio>

namespace definition_body {
    Logger Logger::make() { return Logger{0}; }

    ::std::uint32_t Logger::record() {
        seen += 1;
        std::printf("Logger seen=%u\n", seen);
        return seen;
    }
} // namespace definition_body
