// @generated by pyxis — do not edit

#include "doc_self_links.hpp"

namespace doc_self_links {
    void Container::method() const {
        using fn_t = void (*)(const void*);
        reinterpret_cast<fn_t>(0x10)(this);
    }
} // namespace doc_self_links
