// @generated by pyxis — do not edit

#include "extern_values.hpp"

namespace extern_values {
    DebugFlags*& DebugFlags_get_g_active() {
        return *reinterpret_cast<DebugFlags**>(0x5000);
    }

    Engine*& Engine::get_g_instance() {
        return *reinterpret_cast<Engine**>(0x3000);
    }

    RenderMode*& RenderMode_get_g_current() {
        return *reinterpret_cast<RenderMode**>(0x4000);
    }

    Engine*& get_g_engine() {
        return *reinterpret_cast<Engine**>(0x2000);
    }

    ::std::uint32_t& get_g_frame_count() {
        return *reinterpret_cast<::std::uint32_t*>(0x1000);
    }
} // namespace extern_values
