// @generated by pyxis — do not edit

#include "field_type_name_collision.hpp"

namespace field_type_name_collision {
    void MovieImpl::set_viewport(const ::field_type_name_collision::Viewport* desc) {
        using fn_t = void (*)(void*, const ::field_type_name_collision::Viewport*);
        reinterpret_cast<fn_t>(0x2000)(this, desc);
    }
} // namespace field_type_name_collision
