// @generated by pyxis — do not edit

#include "freestanding_functions.hpp"

namespace freestanding_functions {
    using freestanding_t = void (*)();
    const freestanding_t freestanding = reinterpret_cast<freestanding_t>(0x456);
} // namespace freestanding_functions
