// @generated by pyxis — do not edit

#include "function_pointer_nesting.hpp"

namespace function_pointer_nesting {
    const DispatchVftable* Dispatch::_vftable_ptr() const {
        return this->vftable;
    }

    void (*Dispatch::install(bool (*cb)(Ctx*)))(Ctx*) {
        return _vftable_ptr()->install(this, cb);
    }

    void (*(*Dispatch::table() const)[4])() {
        return _vftable_ptr()->table(this);
    }

    const ShimNamesVftable* ShimNames::_vftable_ptr() const {
        return this->vftable;
    }

    Ctx* ShimNames::via_vftable(Ctx* f, ::std::uint32_t this_) {
        return _vftable_ptr()->via_vftable(this, f, this_);
    }

    void (*ShimNames::via_address(void (*f)(Ctx*), ::std::uint32_t this_))(Ctx*) {
        using fn_t = void (*(*)(void*, void (*)(Ctx*), ::std::uint32_t))(Ctx*);
        return reinterpret_cast<fn_t>(0x6000)(this, f, this_);
    }

    bool (*&get_g_hook())(Ctx*) {
        return *reinterpret_cast<bool (**)(Ctx*)>(0x5000);
    }
} // namespace function_pointer_nesting
