// @generated by pyxis — do not edit

#include "function_pointers.hpp"

namespace function_pointers {
    void (*Callbacks::install(void (*tick)(Engine*, float)))(Engine*, float) {
        using fn_t = void (*(*)(void*, void (*)(Engine*, float)))(Engine*, float);
        return reinterpret_cast<fn_t>(0x2000)(this, tick);
    }

    void Callbacks::seed(::std::uint32_t values[4]) {
        using fn_t = void (*)(void*, ::std::uint32_t [4]);
        reinterpret_cast<fn_t>(0x2001)(this, values);
    }
} // namespace function_pointers
