// @generated by pyxis — do not edit

#include "generics.hpp"
#include "math.hpp"

namespace generics {
    const BoxedRegistryVftable* BoxedRegistry::_vftable_ptr() const {
        return this->vftable;
    }

    void BoxedRegistry::add(Boxed<::math::Vector3> boxed) {
        _vftable_ptr()->add(this, boxed);
    }
} // namespace generics
