// @generated by pyxis — do not edit

#include "member_named_after_type.hpp"

namespace member_named_after_type {
    const DispatcherVftable* Dispatcher::_vftable_ptr() const {
        return this->vftable;
    }

    ::std::uint32_t Dispatcher::Dispatcher_(::std::uint32_t value) {
        return _vftable_ptr()->Dispatcher(this, value);
    }

    bool Teleporter::Teleporter_() {
        using fn_t = bool (*)(void*);
        return reinterpret_cast<fn_t>(0x3000)(this);
    }

    bool Station::Teleporter() {
        return this->base.Teleporter_();
    }
} // namespace member_named_after_type
