// @generated by pyxis — do not edit

#include "qualified_links_provider.hpp"

namespace qualified_links_provider {
    using shared_function_t = void (*)();
    const shared_function_t shared_function = reinterpret_cast<shared_function_t>(0x100);

    ::std::uint32_t*& get_shared_extern() {
        return *reinterpret_cast<::std::uint32_t**>(0x200);
    }
} // namespace qualified_links_provider
