// @generated by pyxis — do not edit

#include "singleton.hpp"

namespace singleton {
    TestType* TestType::singleton() { return *reinterpret_cast<TestType**>(0x13377331); }
} // namespace singleton
