// @generated by pyxis — do not edit

#include "two_base_classes.hpp"

namespace two_base_classes {
    const BaseAVftable* BaseA::_vftable_ptr() const {
        return this->vftable;
    }

    ::std::int32_t BaseA::base_a_vfunc(::std::int32_t a) const {
        return _vftable_ptr()->base_a_vfunc(this, a);
    }

    ::std::int32_t BaseA::base_a_associated(::std::int32_t a) const {
        using fn_t = ::std::int32_t (*)(const void*, ::std::int32_t);
        return reinterpret_cast<fn_t>(0x123)(this, a);
    }

    const BaseBVftable* BaseB::_vftable_ptr() const {
        return this->vftable;
    }

    ::std::int32_t BaseB::base_b_vfunc(::std::int32_t a) const {
        return _vftable_ptr()->base_b_vfunc(this, a);
    }

    ::std::int32_t BaseB::base_b_associated(::std::int32_t a) const {
        using fn_t = ::std::int32_t (*)(const void*, ::std::int32_t);
        return reinterpret_cast<fn_t>(0x456)(this, a);
    }

    const DerivedVftable* Derived::_vftable_ptr() const {
        return reinterpret_cast<const DerivedVftable*>(this->base_a._vftable_ptr());
    }

    ::std::int32_t Derived::base_a_vfunc(::std::int32_t a) const {
        return _vftable_ptr()->base_a_vfunc(this, a);
    }

    ::std::int32_t Derived::derived_vfunc(::std::int32_t a) const {
        return _vftable_ptr()->derived_vfunc(this, a);
    }

    ::std::int32_t Derived::base_a_associated(::std::int32_t a) const {
        return this->base_a.base_a_associated(a);
    }

    ::std::int32_t Derived::base_b_associated(::std::int32_t a) const {
        return this->base_b.base_b_associated(a);
    }

    ::std::int32_t Derived::base_b_vfunc(::std::int32_t a) const {
        return this->base_b.base_b_vfunc(a);
    }

    ::std::int32_t Derived::derived_associated(::std::int32_t a) const {
        using fn_t = ::std::int32_t (*)(const void*, ::std::int32_t);
        return reinterpret_cast<fn_t>(0x789)(this, a);
    }
} // namespace two_base_classes
