// @generated by pyxis — do not edit

#include "unicode.hpp"

namespace unicode {
    const UnicodeVftable* Unicode::_vftable_ptr() const {
        return this->vftable;
    }

    void Unicode::test_vfunc() const {
        _vftable_ptr()->test_vfunc(this);
    }

    void Unicode::test_func() const {
        using fn_t = void (*)(const void*);
        reinterpret_cast<fn_t>(0x123)(this);
    }
} // namespace unicode
