// @generated by pyxis — do not edit

#include "vftable_indices.hpp"

namespace vftable_indices {
    const IndexedVftableVftable* IndexedVftable::_vftable_ptr() const {
        return this->vftable;
    }

    ::std::uint32_t IndexedVftable::first() const {
        return _vftable_ptr()->first(this);
    }

    ::std::int32_t IndexedVftable::second(::std::int32_t x) const {
        return _vftable_ptr()->second(this, x);
    }

    ::std::uint32_t IndexedVftable::third() const {
        return _vftable_ptr()->third(this);
    }
} // namespace vftable_indices
