// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace world::weather {
    struct Weather;
} // namespace world::weather

namespace world::atmosphere {
    struct Atmosphere;

    struct alignas(8) Atmosphere {
        ::world::weather::Weather* weather;
        float temperature;
        float humidity;
    };
    static_assert(sizeof(Atmosphere) == 0x10);
    static_assert(alignof(Atmosphere) == 8);
} // namespace world::atmosphere
