// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace world::weather {
    struct Weather;

    /// Weather state for the world.
    struct alignas(8) Weather {
        float temperature;
        float humidity;
    };
    static_assert(sizeof(Weather) == 0x8);
    static_assert(alignof(Weather) == 8);
} // namespace world::weather
