// @generated by pyxis — do not edit
#pragma once

#include <cstdint>
#include <cstddef>
#include "pyxis_runtime.hpp"

namespace world::deep::marker {
    struct DeepMarker;

    struct alignas(4) DeepMarker {
        ::std::uint32_t value;
    };
    static_assert(sizeof(DeepMarker) == 0x4);
    static_assert(alignof(DeepMarker) == 4);
} // namespace world::deep::marker
